### ISSUE TITLE
`genSources` fails with Loom 1.6 and 1.7 for old Minecraft versions

### ISSUE THREAD

**Issue by SpaceWalkerRS** [FabricMC/fabric-loom#1147]
From the stacktrace it looks like it might be a decompiler cache issue:

```
Caused by: java.lang.RuntimeException: Failed to decompile, java.lang.IllegalStateException: Unexpected output: /paulscode/sound/SoundSystemConfig$Codec.java
        at net.fabricmc.loom.util.ExceptionUtil.createDescriptiveWrapper(ExceptionUtil.java:60)
        at net.fabricmc.loom.task.GenerateSourcesTask.run(GenerateSourcesTask.java:237)
Caused by: java.lang.IllegalStateException: Unexpected output: /paulscode/sound/SoundSystemConfig$Codec.java
        at net.fabricmc.loom.decompilers.cache.CachedJarProcessor.completeJob(CachedJarProcessor.java:185)
        at net.fabricmc.loom.task.GenerateSourcesTask.runWithCache(GenerateSourcesTask.java:288)
        at net.fabricmc.loom.task.GenerateSourcesTask.run(GenerateSourcesTask.java:233)
```

reproduction case (slightly modified example mod): https://github.com/SpaceWalkerRS/loom-1.7-decompile-issue-reproduction-case

**Comment by Juuxel** [comment]
I'd assume it's a broken assumption that `SoundSystemConfig$Codec.class` is the same as `SoundSystemConfig.Codec` in `SoundSystemConfig.java`, which isn't necessarily true in old versions where the inner class metadata is stripped.

This is some related suspicious code (just an example, not sure if it's the cause):
https://github.com/FabricMC/fabric-loom/blob/fa8bf5ede3c8fa3e9d4c524efb974f80e4159367/src/main/java/net/fabricmc/loom/decompilers/cache/JarWalker.java#L91-L99

**Comment by SpaceWalkerRS** [comment]
that definitely looks potentially problematic - would also explain why this isn't an issue with newer versions: Mojang stopped stripping inner class attributes all the way back in 1.8.2-pre5
