### ISSUE TITLE
GradleUtils.getDependencyProject not working for typesafe project accessors

### ISSUE THREAD

**Issue by derklaro** [FabricMC/fabric-loom#1184]
When Minecraft is being set up loom tries to resolve the mods that are added as dependencies into the project. However, when adding a dependency using a typesafe project accessor like:
```kts
"runtimeImpl"(projects.ext.adventureHelper)
```
the code breaks while using reflection to get the dependency project. This seems to be the case as typesafe project accessors actually don't extend `DefaultProjectDependency` directly but rather extend `DelegatingProjectDependency`. This leads to the following error being raised:
```
Caused by: java.lang.IllegalArgumentException: Can not get final org.gradle.api.internal.project.ProjectInternal field org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.dependencyProject on org.gradle.accessors.dm.Ext_AdventureHelperProjectDependency
	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.newGetIllegalArgumentException(MethodHandleFieldAccessorImpl.java:86)
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:61)
	at net.fabricmc.loom.util.gradle.GradleUtils.getDependencyProject(GradleUtils.java:102)
	at net.fabricmc.loom.configuration.processors.SpecContextImpl.getDependentMods(SpecContextImpl.java:89)
	at net.fabricmc.loom.configuration.processors.SpecContextImpl.create(SpecContextImpl.java:63)
	at net.fabricmc.loom.configuration.processors.MinecraftJarProcessorManager.create(MinecraftJarProcessorManager.java:70)
	at net.fabricmc.loom.configuration.CompileConfiguration.setupMinecraft(CompileConfiguration.java:177)
	at net.fabricmc.loom.configuration.CompileConfiguration.lambda$run$1(CompileConfiguration.java:109)
	... 174 more
``` 

It seems like the project accessors are generated [here](https://github.com/gradle/gradle/blob/53afef85c1c36406b0e5132d6be7f306ff451fb4/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/catalog/ProjectAccessorsSourceGenerator.java) which shows that those are extending DelegatingProjectDependency and are not a DefaultProjectDependency directly.

I wasn't sure if just catching the exception or trying to resolve the dependency by recursively trying to resolve via the `delegate` field was the better solution, so I thought I'm just gonna open the issue instead. If you want, I would take a look into proving a pull request to resolve the issue as well.

**Comment by modmuss50** [comment]
Thanks for the issue, yes I think the fix is to do as you say as resolve the delgate, I thought it was easier for me to fix it while I was looking at it. I also went ahead and added a unit test.
