### ISSUE TITLE
ClosedFileSystemException during remap not caught

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-loom#1199]
https://pastes.dev/ArcYUEx8OC

```
Caused by: java.nio.file.ClosedFileSystemException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1635)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.createDirectory(ZipFileSystem.java:711)
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.createDirectory(ZipPath.java:742)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.createDirectory(ZipFileSystemProvider.java:186)
        at net.fabricmc.tinyremapper.OutputConsumerPath.createParentDirs(OutputConsumerPath.java:234)
        at net.fabricmc.tinyremapper.OutputConsumerPath.access$300(OutputConsumerPath.java:42)
        at net.fabricmc.tinyremapper.OutputConsumerPath$1.visitFile(OutputConsumerPath.java:164)
        at net.fabricmc.tinyremapper.OutputConsumerPath$1.visitFile(OutputConsumerPath.java:146)
        at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:146)
        at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:130)
        at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:122)
        at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:114)
        at net.fabricmc.loom.task.RemapJarTask$RemapAction.remap(RemapJarTask.java:293)
        at net.fabricmc.loom.task.RemapJarTask$RemapAction.execute(RemapJarTask.java:245)
```

**Comment by modmuss50** [comment]
This isnt possible to fix as we cannot access the Gradle services we need from within an async work action. We could fork the JVM but then its going to be much slower.
