### ISSUE TITLE
Fabric trying to unzip a .pom dependency

### ISSUE THREAD

**Issue by NGSpace** [FabricMC/fabric-loom#1200]
Uncaught exception in thread "main"
net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: java.io.IOException: error reading /home/computer/.gradle/caches/modules-2/files-2.1/org.graalvm.polyglot/js/24.1.1/c409c1cba080c71c6ca178b762406bcc1ca9352f/js-24.1.1.pom
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:241)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:175)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.io.IOException: error reading /home/computer/.gradle/caches/modules-2/files-2.1/org.graalvm.polyglot/js/24.1.1/c409c1cba080c71c6ca178b762406bcc1ca9352f/js-24.1.1.pom
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:216)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:163)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:190)
	... 5 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1695)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1703)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1541)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:194)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:203)
	... 7 more

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
