### ISSUE TITLE
`ZipFile invalid LOC header (bad signature)` when using accessWidener

### ISSUE THREAD

**Issue by globau** [FabricMC/fabric-loom#1208]
Loom: v0.5.43 Build(release # 43)
Loader: v0.11.1

When I have an accessWidener configured in my `build.gradle`:
```
loom {
    accessWidener "src/main/resources/qol.accesswidener"
}
```
my build fails with: `ZipFile invalid LOC header (bad signature)`.

Removing the `accessWidener` entry results in a successful build.

At first glance this would appear to be due to a corrupt jar.  However, this does not appear to be the case.  I have regenerated the sources after clearing caches multiple times.

I don't have any issues manually extracting the `log4j-provider.properties` file from the jar (see the end of the output below) – **the jar isn't corrupt**.

```
> Configure project :
Fabric Loom: 0.5.43 Build(release FabricMC/fabric-loader#43)
:setting up loom dependencies
:setting up mappings (yarn 1.16.5+build.1)
Using project based jar storage

> Task :compileJava FAILED
Unable to read jar:file:/Users/byron/development/mc-qol/.gradle/loom-cache/1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.1-v2/minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.1-v2.jar!/META-INF/log4j-provider.properties
java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:912)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:923)
        at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:445)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at java.base/java.util.Properties$LineReader.readLine(Properties.java:503)
        at java.base/java.util.Properties.load0(Properties.java:419)
        at java.base/java.util.Properties.load(Properties.java:408)
        at org.apache.logging.log4j.util.PropertiesUtil.loadClose(PropertiesUtil.java:80)
        at org.apache.logging.log4j.util.ProviderUtil.loadProvider(ProviderUtil.java:79)
        at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:66)
        at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:124)
        at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:108)
        at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:89)
        at org.spongepowered.asm.mixin.struct.AnnotatedMethodInfo.<clinit>(AnnotatedMethodInfo.java:43)
        at org.spongepowered.tools.obfuscation.MixinObfuscationProcessorInjection.getSupportedAnnotationTypes(MixinObfuscationProcessorInjection.java:54)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.getSupportedAnnotationTypes(DelegatingProcessor.java:47)
        at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.getSupportedAnnotationTypes(NonIncrementalProcessor.java:33)
        [snip]
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.ExceptionInInitializerError

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
make: *** [build/libs/glob-qol-0.0.0.jar] Error 1
```

```
glob development/mc-qol$ jar -f .gradle/loom-cache/1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.1-v2/minecraft-1.16.5-projectmapped-net.fabricmc.yarn-1.16.5+build.1-v2.jar -x META-INF/log4j-provider.properties
glob development/mc-qol$ ls -l META-INF/log4j-provider.properties
-rw-r--r--  1 byron  staff  904 31 Jan 00:09 META-INF/log4j-provider.properties
```

I see the error regardless of the contents of my `qol.accesswidener` file; right now it's just:
```
accessWidener v1 named
```

Something that stands out to me is `Using project based jar storage` only appears when using `accessWidener`; here's the same build without `accessWidener` in `build.gradle`:
```
> Configure project :
Fabric Loom: 0.5.43 Build(release FabricMC/fabric-loader#43)
:setting up loom dependencies
:setting up mappings (yarn 1.16.5+build.1)

> Task :compileJava
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2
...
```

**Comment by globau** [comment]
This might be a gradle issue - building without the daemon (`./gradlew --no-daemon build`) works successfully.

**Comment by globau** [comment]
Upgrading gradlew from 6.6.1 to 6.8.1 resolved this issue.  Sorry about the spam!

**Comment by pravatk** [comment]
Seeing this issue with gradle 8.10.2
```
------------------------------------------------------------
Gradle 8.10.2
------------------------------------------------------------

Build time:    2024-09-23 21:28:39 UTC
Revision:      415adb9e06a516c44b391edff552fd42139443f7

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.4 (Homebrew 21.0.4)
Daemon JVM:    /opt/homebrew/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 15.0.1 aarch64
```

But running with `--no-daemon` works successfully

**Comment by Player3324** [comment]
This may be due to concurrent access somehow? I.e. the file is being written concurrently and than log4j's plugin system loads ist at an unexpected time. It'd be great if we can somehow just disable that plugin system...

Moving the issue to loom for now.

**Comment by modmuss50** [comment]
Log4j shouldnt even be on the annotation processor classpath. @pravatk could you please run `gradlew.bat dependencies --configuration annotationProcessor` and post your results.

I get the following using Loom 1.8.12 (note no log4j):

```
+--- org.ow2.asm:asm:9.7.1
+--- org.ow2.asm:asm-analysis:9.7.1
+--- org.ow2.asm:asm-commons:9.7.1
+--- org.ow2.asm:asm-tree:9.7.1
|    \--- org.ow2.asm:asm:9.7.1
+--- org.ow2.asm:asm-util:9.7.1
+--- net.fabricmc:sponge-mixin:0.15.4+mixin.0.8.7
+--- io.github.llamalad7:mixinextras-fabric:0.4.1
\--- net.fabricmc:fabric-mixin-compile-extensions:0.6.0
     +--- net.fabricmc:mapping-io:0.2.1
     |    \--- org.ow2.asm:asm:9.1 -> 9.7.1
     +--- net.fabricmc:sponge-mixin:0.11.4+mixin.0.8.5 -> 0.15.4+mixin.0.8.7
     +--- org.ow2.asm:asm-tree:9.4 -> 9.7.1 (*)
     \--- org.ow2.asm:asm:9.4 -> 9.7.1
```

A new stacktrace/log would also be very helpful as the one above is from a 4 year old version of loom.

**Comment by modmuss50** [comment]
Old issue, please open a new one if this is still a problem.
