### ISSUE TITLE
[0.2.5] unable to update workspace to a new Minecraft version

### ISSUE THREAD

**Issue by UpcraftLP** [FabricMC/fabric-loom#122]
when updating from 1.14.3 to 1.14.4 I get a nullpointer exception for gradle not finding the 1.14.4 info json file.
`D:\.gradle\caches\fabric-loom\minecraft-1.14.4-info.json (The system cannot find the file specified)`
(the gradle cache is in a custom location, altho that shouldn't be relevant to this issue as it is still looking in the right place)

```
Fabric Loom: 0.2.5-SNAPSHOT Build(jenkins #10)
:setting up loom dependencies

* What went wrong:
> Failed to notify project evaluation listener.
   > Failed to provide com.mojang:minecraft:1.14.4
   > java.lang.NullPointerException (no error message)
```

relevant part of the stacktrace:
```
Caused by: java.lang.RuntimeException: Failed to provide com.mojang:minecraft:1.14.4
	at net.fabricmc.loom.util.LoomDependencyManager.lambda$handleDependencies$1(LoomDependencyManager.java:107)
	at net.fabricmc.loom.util.LoomDependencyManager.handleDependencies(LoomDependencyManager.java:101)
	at net.fabricmc.loom.AbstractPlugin.lambda$configureCompile$11(AbstractPlugin.java:298)


Caused by: java.io.FileNotFoundException: D:\.gradle\caches\fabric-loom\minecraft-1.14.4-info.json (The system cannot find the file specified)
	at net.fabricmc.loom.providers.MinecraftProvider.provide(MinecraftProvider.java:69)
	at net.fabricmc.loom.util.LoomDependencyManager.lambda$handleDependencies$1(LoomDependencyManager.java:105)
```

**Comment by UpcraftLP** [comment]
Found a workaround by temporarily downgrading to loom 0.2.4, once the initial setup has completed successfully it's fine to go back to 0.2.5.
