### ISSUE TITLE
Certain dependency versions get retroactively removed from dependencies

### ISSUE THREAD

**Issue by Khitiara** [FabricMC/fabric-loom#124]
Depending on fabric-language-scala version 0.2.0.9 from modmuss' maven results in the dependency never being resolved, and it is not added to classpath in modCompile or included nin a final jar when used with include. Compiling fabric-language-scala locally with a different version number and listing that on dependencies causes no issues.

Issue was observed in https://github.com/robotbrain/luminiferous-uplands

**Comment by Khitiara** [comment]
Now confirmed with multiple machines and libraries

**Comment by Khitiara** [comment]
```
C:\programs\ether>gradlew --warning-mode=all runClient
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.5.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
Fabric Loom: 0.2.4-SNAPSHOT Build(jenkins #10)
:setting up loom dependencies
:setting up mappings (yarn 1.14.4+build.4)
:providing net.fabricmc.fabric-api:fabric-api:0.3.0+build.207 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-api-base:0.1.0+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-biomes-v1:0.1.0+896c7fbb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-commands-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-containers-v0:0.1.2+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-content-registries-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-crash-report-info-v1:0.1.0+5914746342 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-events-interaction-v0:0.1.0+ea100f6142 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-events-lifecycle-v0:0.1.0+5914746342 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-item-groups-v0:0.1.0+1e69a0a542 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-keybindings-v0:0.1.1+7dfef87c42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-loot-tables-v1:0.1.0+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-mining-levels-v0:0.1.0+ab421b9c42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-models-v0:0.1.0+5914746342 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-networking-blockentity-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-networking-v0:0.1.2+9b03381f42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-object-builders-v0:0.1.1+9b03381f42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-registry-sync-v0:0.2.2+9b03381f42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-renderer-api-v1:0.1.1+9b03381f42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-renderer-indigo:0.1.9+9b03381f42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-rendering-data-attachment-v1:0.1.0+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-rendering-fluids-v1:0.1.0+dc4c57c242 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-rendering-v0:0.1.1+6dad974e42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-resource-loader-v0:0.1.1+7495ea2842 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-tag-extensions-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-textures-v0:0.1.4+b494ebeb42 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc:fabric-loader:0.4.8+build.159 (net.fabricmc.yarn.1_14_4.4)
:providing me.shedaniel:RoughlyEnoughItems:2.9.7+build.143 (net.fabricmc.yarn.1_14_4.4)
:providing io.github.cottonmc:LibGui:1.2.3 (net.fabricmc.yarn.1_14_4.4)
:providing org.scala-lang:scala-compiler:2.12.8
:providing org.scala-lang:scala-reflect:2.12.8
:providing org.scala-lang.modules:scala-swing_2.12:2.1.1
:providing org.scala-lang.modules:scala-xml_2.12:1.0.6
:providing org.scala-lang:scala-library:2.12.8
:providing cloth:ClothEvents:0.3.1.23 (net.fabricmc.yarn.1_14_4.4)
:providing blue.endless:jankson:1.1.0
:providing cloth-config:ClothConfig2:0.2.0 (net.fabricmc.yarn.1_14_4.4)
:providing io.github.prospector.modmenu:ModMenu:1.5.4-85 (net.fabricmc.yarn.1_14_4.4)
:providing io.github.cottonmc:Jankson:1.0.0+j1.1.2 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc:tiny-mappings-parser:0.1.1.8
:providing net.fabricmc:sponge-mixin:0.7.11.20
:providing net.fabricmc:tiny-remapper:0.1.0.33
:providing net.fabricmc:fabric-loader-sat4j:2.3.5.4
:providing com.google.jimfs:jimfs:1.1
:providing org.ow2.asm:asm:7.1
:providing org.ow2.asm:asm-analysis:7.1
:providing org.ow2.asm:asm-commons:7.1
:providing org.ow2.asm:asm-tree:7.1
:providing org.ow2.asm:asm-util:7.1
:providing com.jamieswhiteshirt:developer-mode:1.0.14 (net.fabricmc.yarn.1_14_4.4)
:providing net.fabricmc.fabric-api:fabric-api:0.3.0+build.207 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-api-base:0.1.0+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-biomes-v1:0.1.0+896c7fbb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-commands-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-containers-v0:0.1.2+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-content-registries-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-crash-report-info-v1:0.1.0+5914746342 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-events-interaction-v0:0.1.0+ea100f6142 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-events-lifecycle-v0:0.1.0+5914746342 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-item-groups-v0:0.1.0+1e69a0a542 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-keybindings-v0:0.1.1+7dfef87c42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-loot-tables-v1:0.1.0+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-mining-levels-v0:0.1.0+ab421b9c42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-models-v0:0.1.0+5914746342 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-networking-blockentity-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-networking-v0:0.1.2+9b03381f42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-object-builders-v0:0.1.1+9b03381f42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-registry-sync-v0:0.2.2+9b03381f42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-renderer-api-v1:0.1.1+9b03381f42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-renderer-indigo:0.1.9+9b03381f42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-rendering-data-attachment-v1:0.1.0+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-rendering-fluids-v1:0.1.0+dc4c57c242 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-rendering-v0:0.1.1+6dad974e42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-resource-loader-v0:0.1.1+7495ea2842 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-tag-extensions-v0:0.1.1+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc.fabric-api:fabric-textures-v0:0.1.4+b494ebeb42 (net.fabricmc.yarn.1_14_4.4) sources
:providing net.fabricmc:fabric-loader:0.4.8+build.159 (net.fabricmc.yarn.1_14_4.4) sources
:providing io.github.cottonmc:LibGui:1.2.3 (net.fabricmc.yarn.1_14_4.4) sources
:providing io.github.cottonmc:Jankson:1.0.0+j1.1.2 (net.fabricmc.yarn.1_14_4.4) sources
:providing com.jamieswhiteshirt:developer-mode:1.0.14 (net.fabricmc.yarn.1_14_4.4) sources

> Task :compileJava
:setting java compiler args
Could not find refmap definition, will be using default name: ether-refmap.json
Note: SpongePowered MIXIN Annotation Processor Version=0.7.11
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading named:intermediary mappings from C:\Users\RoboSky\.gradle\caches\fabric-loom\mappings\net.fabricmc.yarn-tiny-1.14.4-4
Note: Writing refmap to C:\programs\ether\build\classes\java\main\ether-refmap.json
Note: Writing refmap to C:\programs\ether\build\classes\java\main\ether-refmap.json
Note: Writing named:intermediary output TinyMappings to C:\programs\ether\build\loom-cache\mixin-map-1.14.4-4.tiny
Note: Writing refmap to C:\programs\ether\build\classes\java\main\ether-refmap.json
Note: Writing refmap to C:\programs\ether\build\classes\java\main\ether-refmap.json
Note: Writing named:intermediary output TinyMappings to C:\programs\ether\build\loom-cache\mixin-map-1.14.4-4.tiny

> Task :downloadAssets
:downloading assets...

> Task :runClient
[09:37:15] [main/INFO]: Loading for game Minecraft 1.14.4
[09:37:16] [main/WARN]: Warnings were found!
 - Mod roughlyenoughitems recommends mod {cloth-config @ [>=0.1.0]}, which is missing!
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod luminiferous_uplands depends on mod {fabric-language-scala @ [*]}, which is missing!
 - Mod roughlyenoughitems recommends mod {cloth-config @ [>=0.1.0]}, which is missing!
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:324)
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
        ... 2 more

> Task :runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-8.0.212.04-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
6 actionable tasks: 3 executed, 3 up-to-date
```

**Comment by Khitiara** [comment]
Issue found and resolved
