### ISSUE TITLE
"Duplicate versions for mod ID" errors when switching between minecraft/fabric api versions

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric-loom#151]
This is the error
```
[00:48:00] [main/INFO]: Loading for game Minecraft 1.14.4
net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'fabric-biomes-v1': [0.1.0+896c7fbb42 at /C:/Users/natan/Desktop/Fabricated-Energistics/.gradle/loom-cache/remapped_mods/net.fabricmc.yarn.1_14_4.1.14.4+build.15-v2.net.fabricmc.fabric-api.fabric-biomes-v1-0.1.0+896c7fbb42.jar], [0.1.0+591e97ae42 at /C:/Users/natan/Desktop/Fabricated-Energistics/.gradle/loom-cache/remapped_mods/net.fabricmc.yarn.1_14_4.1.14.4+build.15-v2.net.fabricmc.fabric-api.fabric-biomes-v1-0.1.0+591e97ae42.jar]
	at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:87)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:97)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:84)
```

It happened after switching to minecraft 1.15, running the game, and then switching back to minecraft 1.14 (While changing fabric api versions appropriately). 
Running `gradlew --stop` did not fix it. 
After I deleted the loom cache I got a "Failed to remap mod" error. 
When I run `gradlew --stacktrace` there was not such error, but, some fabric api packages were not being recognized by IDEA.  
So I delete the loom cache again and run `gradlew --stacktrace`, and I get more errors: https://hasteb.in/fagupato.cs.  The main thing being:
```
Caused by: java.nio.file.FileSystemException: C:\Users\natan\Desktop\Fabricated-Energistics\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.1_14_4.1.14.4+build.15-v2.com.lettuce.fudg
e.fabric-drawer-3.1.0.jar: The process cannot access the file because it is being used by another process.
```
I closed IDEA and ran `gradlew` again, and now I get the same error but slightly different: 
```
net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'fabric-biomes-v1': [0.1.0+896c7fbb42 at /C:/Users/natan/Desktop/Fabricated-Energistics/.gradle/loom-cache/remapped_mods/net.fabricmc.yarn.1_14_4.1.14.4+build.15-v2.net.fabricmc.fabric-api.fabric-biomes-v1-0.1.0+896c7fbb42.jar], [0.1.0+591e97ae42 at /C:/Users/natan/Desktop/Fabricated-Energistics/.gradle/loom-cache/remapped_mods/net.fabricmc.yarn.1_14_4.1.14.4+build.15-v2.net.fabricmc.fabric-api.fabric-biomes-v1-0.1.0+591e97ae42.jar]
	at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:87)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:97)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:84)
```

**Comment by natanfudge** [comment]
The problem is because of REI pulling its own fabric api, but I excluded fabric api, weird...

**Comment by modmuss50** [comment]
If this is still an issue please open a new ticket.
