### ISSUE TITLE
FernFlower decompilation multithreading npe?

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-loom#223]
https://gist.github.com/ed692ca4e6e822e9a64a31e44536e195
These issues aren't produced consistently but rather at chance. Tested with mapping 1.16 pre 5 build 2 gradle 6.3 and loom 0.4.25.

**Comment by octylFractal** [comment]
Similar issue:
```java
Class net/minecraft/world/gen/chunk/StrongholdConfig couldn't be fully decompiled.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:301)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:114)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$0(ContextUnit.java:143)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by modmuss50** [comment]
Pushed an update to loom that should help, can you please try again (with 0.4.26) and let me know if you still have issues. (If you do post the log again)

Thanks.

**Comment by liach** [comment]
Tested genSources on 1.16 pre 6 build 3 with gradle 6.3 and loom 0.4.26 for 4 runs. No exception occured. Will just reopen if I happen to reproduce it again.
