### ISSUE TITLE
No refmaps generated with kotlin & kapt

### ISSUE THREAD

**Issue by PssbleTrngle** [FabricMC/fabric-loom#239]
When I build the mod jar, kapt is running, but when I try to run the mod in production, I get the following error, suggesting their was no refmap generated

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on stop could not find any targets matching 'Lnet/minecraft/server/MinecraftServer;stop(Z)V' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> webcommands.mixin.json:MinecraftServerMixin -> Prepare Injections ->  -> handler$zbd000$stop(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543)
 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280)
 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259)
 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
 	at jdk.internal.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:139)
 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:595)
 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1236)
 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
```

[Full log](https://pastebin.com/UMWcjyVW)
[build.gradle](https://github.com/PssbleTrngle/WebCommands/blob/develop/build.gradle)
[gradle.properties](https://github.com/PssbleTrngle/WebCommands/blob/develop/gradle.properties)

Loom Version:  0.4.33
Kotlin Version: 1.3.70
fabric_kotlin Version: 1.3.72+build.1

**Comment by natanfudge** [comment]
Kotlin mixins are not supported...

**Comment by modmuss50** [comment]
Mixins are not supported in kotlin, you can make a minimal mixin in java that calls your kotlin code.

**Comment by EmptyDreams** [comment]
> Mixins are not supported in kotlin, you can make a minimal mixin in java that calls your kotlin code.

I'm curious why using Mixin with Kotlin works fine in the development environment, but it's not supported in the production environment 🤔
