### ISSUE TITLE
Loom's include doesn't include required transitive dependency jars.

### ISSUE THREAD

**Issue by jaideepheer** [FabricMC/fabric-loom#242]
I want to `include` ['org.hibernate.validator:hibernate-validator'](https://mvnrepository.com/artifact/org.hibernate.validator/hibernate-validator/6.1.5.Final). I added its `include` in my dependencies in `build.gradle` like this :-
```
...
dependencies {
...
        include("org.hibernate.validator:hibernate-validator:6.1.5.Final")
	implementation("org.hibernate.validator:hibernate-validator:6.1.5.Final")

        // javax.el for hibernate-validator, this is a dependency that hibernate specifies should be separately included
	include("org.glassfish:javax.el:+")
	implementation("org.glassfish:javax.el:+")
...
}
...
```
Then I ran `gradlew build` to build my mod's jar. In my mod's jar `/META-INF/jars/hibernate-validator-6.1.5.Final.jar` file is present. But when I put the mod in a mods folder and run the game I get the following error :- 
```
...
Caused by: java.lang.NoClassDefFoundError: javax/validation/Validation
	at dev.jaideep.game.minecraft.fabric.splan.ModInit.onInitializeClient(ModInit.java:25)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.ClassNotFoundException: javax.validation.Validation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at
...
```
I have tried adding `include("javax.validation:validation-api:+")` to my build file but then I get a new error for different required dependency.
```
...
Caused by: java.lang.NoClassDefFoundError: org/jboss/logging/BasicLogger
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at
...
```

The mod works fine in the dev workspace. I can launch it and it loads all the libraries. I can even see all these libraries in the External Libraries menu of IntelliJ. This means that `implementation` is working but the `include` task is not including dependencies' jars.

**Comment by JamiesWhiteShirt** [comment]
This is by design. Libraries you might target with 'include' often depend on libraries that are already used by Minecraft such as guava. Including libraries that already present on the classpath has catastrophic results that you will not notice until you try it outside a development environment.

**Comment by jaideepheer** [comment]
can't loom just skip loading libraries that are already present on the classpath? This way my jar can have multiple libraries and loom only loads the ones that do not conflict with the classpath.

Another solution would be to detect the libraries already on the classpath while building so that conflicting jars are never added to the mod.

**Comment by modmuss50** [comment]
This is by design. I think you should know exactally what is going in your jar, it would be too easy to include stuff you really dont want. And ways around that would be fragile.
