### ISSUE TITLE
Run tasks don't work with Kotlin dependencies

### ISSUE THREAD

**Issue by Martmists-GH** [FabricMC/fabric-loom#275]
to reproduce:

```gradle
repositories {
    maven {
        name = "Gunpowder"
        url = "https://maven.martmists.com/releases"
    }
}

dependencies {
    modRuntime "io.github.gunpowder:gunpowder-base:${project.gunpowder}+${project.minecraft}"
}
```

error:

```

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'gunpowder-base'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.LinkageError: loader constraint violation: loader net.fabricmc.loader.launch.knot.KnotClassLoader @42bc14c1 wants to load class kotlin.jvm.internal.DefaultConstructorMarker. A different class with the same name was previously loaded by 'app'. (kotlin.jvm.internal.DefaultConstructorMarker is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.<clinit>(KDeclarationContainerImpl.kt:285)
	at kotlin.reflect.jvm.internal.KClassCacheKt.getOrCreateKotlinClass(kClassCache.kt:62)
	at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.getOrCreateKotlinClass(ReflectionFactoryImpl.java:50)
	at kotlin.jvm.internal.Reflection.getOrCreateKotlinClass(Reflection.java:59)
	at shadow.jetbrains.exposed.sql.Database.<clinit>(Database.java:62)
	at io.github.gunpowder.entities.GunpowderDatabase.loadDatabase(GunpowderDatabase.java:95)
	at io.github.gunpowder.mod.AbstractGunpowderMod.initialize(AbstractGunpowderMod.java:56)
	at io.github.gunpowder.mod.client.GunpowderClientMod.onInitializeClient(GunpowderClientMod.java:51)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 12 more

```

Note that this only happens in dev, when building and running in production it all works fine.

**Comment by modmuss50** [comment]
If this is still an issue please open a new issue.

**Comment by modmuss50** [comment]
I believe I looked into this, and it was caused by the mod using kotlin from a mixin plugin.
