### ISSUE TITLE
Dev client fails to remap some mixin shadows from incoming dependencies

### ISSUE THREAD

**Issue by zml2008** [FabricMC/fabric-loom#344]
With loom 0.6.35, using official names, when trying to execute runClient, I get this mixin application failure.

It seems to persist even when running after a `--refresh-dependencies`.

This is coming from trying to update https://github.com/KyoriPowered/adventure-platform-fabric to the new loom release.

```
[00:43:03] [main/FATAL] (mixin) Mixin apply failed fabric-biomes-v1.mixins.json:MixinBiomeSource -> <mojmap BiomeSource>: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_9391 was not located in the target class <mojmap BiomeSource>. Using refmap fabric-biomes-v1-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_9391 was not located in the target class <mojmap BiomeSource>. Using refmap fabric-biomes-v1-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.1.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at <mojmap Registry>.lambda$static$42(.java:202) ~[minecraft-1.16.5-mapped-net.minecraft.mappings-1.16.5-v2.jar:?]
	at <mojmap Registry>.lambda$static$46(.java:350) ~[minecraft-1.16.5-mapped-net.minecraft.mappings-1.16.5-v2.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) [?:?]
	at <mojmap Registry>.<clinit>(.java:349) [minecraft-1.16.5-mapped-net.minecraft.mappings-1.16.5-v2.jar:?]
	at <mojmap Bootstrap.init>(.java:37) [minecraft-1.16.5-mapped-net.minecraft.mappings-1.16.5-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:121) [minecraft-1.16.5-mapped-net.minecraft.mappings-1.16.5-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by zml2008** [comment]
a quick update, seems this is still occurring after rolling back to Loom 0.5

**Comment by modmuss50** [comment]
Humm, could be an issue with the runtime mixin remapping, its always been a bit flaky on fields. Ill take a closer look.

**Comment by modmuss50** [comment]
@zml2008 idk if im just blind but I cannot find where the loom version is defined in the project you linked 😟

**Comment by zml2008** [comment]
hm, this is weird. kinda off a hunch, seems it was my attempted hack at https://github.com/KyoriPowered/adventure-platform-fabric/blob/master/build.gradle.kts#L50 to have the full fabric API available to my testmod source set without being included into the pom that led to this issue. Replacing those two lines with a `modImplementation` declaration seems to make the client run properly. fairly odd issue though still imo

(for reference since i have a bit of a... uh.. sprawl... of gradle plugins for my projects, https://github.com/zml2008/gradle-plugins/blob/dev/opinionated-fabric/build.gradle.kts#L11 is where I declare the loom version and it's brought in as a transitive dependency)
