### ISSUE TITLE
Mappings are not loaded when running debug session in Visual Studio Code using Mojang mappings

### ISSUE THREAD

**Issue by bytzo** [FabricMC/fabric-loom#418]
EDIT:
I forgot to mention the Loom version. This was tested with Loom 0.8, however I have seen the issue occur in 0.5, 0.6, and 0.7. I have not tested 0.9.

When running a debug session inside of Visual Studio Code using Mojang mappings, mappings are not loaded. This can cause issues when attempting to load other mods in the debug session (such as the Fabric API). The Fabric Loader will print `Mappings not present!` in the logs.

1. Clone the Fabric Example Mod (I tested this with [`fda2a1c`](https://github.com/FabricMC/fabric-example-mod/commit/fda2a1cf1e329ed33f111d3e29d3269faf94d597). [`fda2a1c`](https://github.com/FabricMC/fabric-example-mod/commit/fda2a1cf1e329ed33f111d3e29d3269faf94d597) uses Loom 0.8.).
2. Use `minecraft.officialMojangMappings()` as the mappings in `build.gradle`. Remove `ExampleMixin` for now, or change it from Yarn to Mojang Mappings.
3. Run the `vscode` Gradle task.
4. Open Visual Studio Code with the Java Extension Pack and open the Fabric Example Mod folder. Wait for the project to build.
5. Run the debug session using `F5`. Notice how the debug session crashes. Check for `Mappings not present!` in the logs.
<details>
<summary>Log Output from above steps <i>(warning to Yarn contributors: contains Mojang Mappings)</i></summary>
<pre>
[22:28:20] [main/INFO] (FabricLoader) Loading for game Minecraft 1.17
[22:28:20] [main/INFO] (Fabric|Loader) [FabricLoader] Loading 48 mods: fabric-screen-handler-api-v1@1.1.8+a02b4463d5, minecraft@1.17, fabric-networking-blockentity-v0@0.2.11+a02b4463d5, fabric-renderer-api-v1@0.4.2+a02b4463d5, fabric-keybindings-v0@0.2.2+36b77c3ed5, fabric-command-api-v1@1.1.1+a02b4463d5, fabricloader@0.11.3, fabric-screen-api-v1@1.0.3+b7ab6121d5, fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5, fabric-renderer-indigo@0.4.8+a02b4463d5, fabric-structure-api-v1@1.1.10+be9da310d5, fabric-containers-v0@0.1.12+a02b4463d5, fabric-object-builder-api-v1@1.10.9+b7ab6121d5, fabric-dimensions-v1@2.0.10+a02b4463d5, java@16, fabric-events-interaction-v0@0.4.8+a02b4463d5, fabric-item-api-v1@1.2.4+a02b4463d5, fabric-crash-report-info-v1@0.1.5+be9da310d5, fabric-game-rule-api-v1@1.0.6+a02b4463d5, fabric-entity-events-v1@1.1.0+a02b4463d5, fabric-api-base@0.3.0+a02b4463d5, fabric-rendering-v0@1.1.2+92519afad5, fabric-key-binding-api-v1@1.0.4+a02b4463d5, fabric-rendering-v1@1.6.0+a02b4463d5, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, fabric-resource-loader-v0@0.4.7+b7ab6121d5, fabric-textures-v0@1.0.6+a02b4463d5, fabric-content-registries-v0@0.2.2+a02b4463d5, fabric-tag-extensions-v0@1.1.4+a02b4463d5, fabric-biome-api-v1@3.1.11+9e521e13d5, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, fabric-registry-sync-v0@0.7.9+a02b4463d5, fabric-commands-v0@0.2.2+92519afad5, modid@${version}, fabric-blockrenderlayer-v1@1.1.5+a02b4463d5, fabric-lifecycle-events-v1@1.4.4+a02b4463d5, fabric-mining-levels-v0@0.1.3+92519afad5, fabric-renderer-registries-v1@3.2.0+a02b4463d5, fabric-networking-api-v1@1.0.11+b7ab6121d5, fabric-events-lifecycle-v0@0.2.1+92519afad5, fabric-loot-tables-v1@1.0.4+a02b4463d5, fabric@0.34.9+1.17, fabric-item-groups-v0@0.2.10+b7ab6121d5, fabric-models-v0@0.3.0+a02b4463d5, fabric-particles-v1@0.2.4+a02b4463d5, fabric-object-builders-v0@0.7.3+a02b4463d5, fabric-networking-v0@0.3.2+92519afad5, fabric-api-lookup-api-v1@1.0.2+a02b4463d5
[22:28:20] [main/WARN] (Fabric|Loader) Mod `modid` (${version}) does not respect SemVer - comparison support is limited.
[22:28:20] [main/INFO] (FabricLoader) Mappings not present!
[22:28:20] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/bytzo/.local/share/gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/12c437eebf031967eaa7daad861e115932772cc7/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[22:28:20] [main/WARN] (mixin) The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[22:28:20] [main/INFO] (mixin) Compatibility level set to JAVA_16
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_3218$class_5526 (java.lang.ClassNotFoundException: net/minecraft/class_3218$class_5526)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_3218$class_5526 was not found fabric-lifecycle-events-v1.mixins.json:ServerWorldEntityLoaderMixin
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_638$class_5612 (java.lang.ClassNotFoundException: net/minecraft/class_638$class_5612)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_638$class_5612 was not found fabric-lifecycle-events-v1.mixins.json:client.ClientWorldEntityLoaderMixin
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_778$class_780 (java.lang.ClassNotFoundException: net/minecraft/class_778$class_780)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_778$class_780 was not found fabric-renderer-indigo.mixins.json:MixinAmbientOcclusionCalculator
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_846$class_851$class_4578 (java.lang.ClassNotFoundException: net/minecraft/class_846$class_851$class_4578)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_846$class_851$class_4578 was not found fabric-renderer-indigo.mixins.json:MixinChunkRebuildTask
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_3244$1 (java.lang.ClassNotFoundException: net/minecraft/class_3244$1)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_3244$1 was not found fabric-events-interaction-v0.mixins.json:MixinServerPlayNetworkHandler
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_3853$class_4162 (java.lang.ClassNotFoundException: net/minecraft/class_3853$class_4162)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_3853$class_4162 was not found fabric-object-builder-v1.mixins.json:TypeAwareTradeMixin
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_378$1 (java.lang.ClassNotFoundException: net/minecraft/class_378$1)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_378$1 was not found fabric-resource-loader-v0.mixins.json:client.FontManagerResourceReloadListenerMixin
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_3065$1 (java.lang.ClassNotFoundException: net/minecraft/class_3065$1)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_3065$1 was not found fabric-game-rule-api-v1.mixins.json:GameRuleCommandVisitorMixin
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_5235$class_5241$1 (java.lang.ClassNotFoundException: net/minecraft/class_5235$class_5241$1)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_5235$class_5241$1 was not found fabric-game-rule-api-v1.mixins.json:client.RuleListWidgetVisitorMixin
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_3898$class_3208 (java.lang.ClassNotFoundException: net/minecraft/class_3898$class_3208)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_3898$class_3208 was not found fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_702$class_4090 (java.lang.ClassNotFoundException: net/minecraft/class_702$class_4090)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_702$class_4090 was not found fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_2474$class_5124 (java.lang.ClassNotFoundException: net/minecraft/class_2474$class_5124)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_2474$class_5124 was not found fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder
[22:28:20] [main/WARN] (mixin) Error loading class: net/minecraft/class_5120$class_5121 (java.lang.ClassNotFoundException: net/minecraft/class_5120$class_5121)
[22:28:20] [main/WARN] (mixin) @Mixin target net/minecraft/class_5120$class_5121 was not found fabric-tag-extensions-v0.mixins.json:MixinTagImpl
[22:28:21] [main/FATAL] (mixin) Mixin apply failed fabric-entity-events-v1.mixins.json:LivingEntityMixin -> net.minecraft.world.entity.LivingEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_29504 in fabric-entity-events-v1.mixins.json:LivingEntityMixin was not located in the target class net.minecraft.world.entity.LivingEntity. Using refmap fabric-entity-events-v1-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_29504 in fabric-entity-events-v1.mixins.json:LivingEntityMixin was not located in the target class net.minecraft.world.entity.LivingEntity. Using refmap fabric-entity-events-v1-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:423) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:120) [minecraft-1.17-mapped-net.minecraft.mappings-1.17-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
</pre>
</details>

**Comment by modmuss50** [comment]
What loom version are you using?

**Comment by bytzo** [comment]
This was tested in 0.8, but I've also seen the issue occur since 0.5. I have not tested 0.9.

**Comment by AHilyard** [comment]
Just wanted to note that I ran into the exact same issue, I am using Loom 0.9.  In order to work around it, I had to copy _.gradle/caches/fabric-loom/mappings/net.minecraft.mappings-1.17.1.tiny.tiny_ in my user directory to _/bin/main/mappings/mappings.tiny_ in my project directory.  Not sure why that is necessary in vscode and not in other IDEs, but it worked for me.

**Comment by bytzo** [comment]
I no longer encounter this issue when using Loom 0.10.62. @AHilyard, is this also fixed for you in the latest Loom versions? If so, I will close this issue.

**Comment by AHilyard** [comment]
I've tested and can confirm that this is fixed in 0.10.62.
