### ISSUE TITLE
Minecraft fabric

### ISSUE THREAD

**Issue by Lekeko** [FabricMC/fabric-loom#492]
Hello, I was recently starting to make a mod for Minecraft fabric and I stumbled through some errors, firstly my mods weren't loading so I made another project (in Visual Studio Code) imported some java files from the old project to the new project, and now the mod is showing in the debug console but I keep getting this error and tried to find a solution for hours now but I can't fin it.

```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-object-builder-api-v1
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:432)
FabricLoader.java:432
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:135)
Knot.java:135
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
KnotClient.java:28
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Main.java:86
Caused by: java.lang.RuntimeException: Namespace (intermediary) does not match current runtime namespace (named)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:47)
AccessWidenerReader.java:47
	at net.fabricmc.loader.FabricLoader.loadAccessWideners(FabricLoader.java:430)
FabricLoader.java:430
	... 3 more
```

**Comment by nnym** [comment]
Did you declare your Fabric API dependency correctly in your build script (`build.gradle`)? It should be in `modImplementation` or `modApi` (so it would look like `modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_version"`).

**Comment by Lekeko** [comment]
I changed it now from `modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"` to `modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"` but now i have to wait a little because my java debugger takes a lot of time to load for some reason, ill tell you when its ready

**Comment by Lekeko** [comment]
No, it still says the exact same error, do I need to write myself the version of the fabric-api ?

**Comment by Lekeko** [comment]
I decided to start a new project and carefully replace the mod file and everything I did and now it works, thank you for the help, it was much appreciated!!!
