### ISSUE TITLE
ZIP file is kept locked when modifying access winders.

### ISSUE THREAD

**Issue by xxDark** [FabricMC/fabric-loom#499]
```Java
Caused by: java.lang.RuntimeException: Failed to copy source jar
	at net.fabricmc.loom.configuration.processors.MinecraftProcessedProvider.addDependencies(MinecraftProcessedProvider.java:62)
	at net.fabricmc.loom.configuration.providers.minecraft.MinecraftMappedProvider.provide(MinecraftMappedProvider.java:98)
	at net.fabricmc.loom.configuration.providers.mappings.MappingsProviderImpl.provide(MappingsProviderImpl.java:198)
	at net.fabricmc.loom.configuration.LoomDependencyManager.handleDependencies(LoomDependencyManager.java:133)
	... 165 more
Caused by: java.nio.file.FileSystemException: F:\modding\mod\.gradle\loom-cache\1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.39-v2\minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1392)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:885)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:835)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:802)
	at net.fabricmc.loom.configuration.processors.MinecraftProcessedProvider.addDependencies(MinecraftProcessedProvider.java:60)
	... 168 more
````

**Comment by modmuss50** [comment]
Need more info, please re-open if this is still an issue.
