### ISSUE TITLE
Mixin prepare failed preparing ExampleMixin

### ISSUE THREAD

**Issue by Lekeko** [FabricMC/fabric-loom#505]
I have recently renamed the assets folder into data then back to assets but now it gives me this error

`Exception in thread "main" org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [kekospear.mixins.json:ExampleMixin] from phase [DEFAULT] in config [kekospear.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
MixinProcessor.java:642
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:590)
MixinProcessor.java:590
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:517)
MixinProcessor.java:517
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
MixinProcessor.java:439
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
MixinProcessor.java:415
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
MixinProcessor.java:285
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
MixinTransformer.java:208
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
MixinTransformer.java:178
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
FabricMixinTransformerProxy.java:23
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
KnotClassDelegate.java:162
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
KnotClassLoader.java:154
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
ClassLoader.java:519
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:232)
MinecraftGameProvider.java:232
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
Knot.java:153
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
KnotClient.java:28
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Main.java:86
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'keko.keko.spear.mixin.ExampleMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
MixinInfo.java:855
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
MixinConfig.java:715
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652)
MixinConfig.java:652
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514)
MixinProcessor.java:514
	... 13 more
`

![aaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/90535623/134649844-96e4b806-da9d-42e1-9d5f-371eb0310fa0.png)

**Comment by Lekeko** [comment]
it's ok now i found the problem, in kekospear.mixins.json was ExampleMixin and i just deleted it
