### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-content-registries-v0

### ISSUE THREAD

**Issue by Scrobotic** [FabricMC/fabric-loom#529]
Hi, I'm currently making my first minecraft mod with fabric but I'm getting this Error:

Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-content-registries-v0
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:451)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (intermediary) does not match current runtime namespace (named)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:449)
	... 4 more
Disconnected from the target VM, address: '127.0.0.1:58623', transport: 'socket'

Process finished with exit code 1

**Comment by Scrobotic** [comment]
(Pls help!!!)

**Comment by modmuss50** [comment]
Update loom to 0.10-SNAPSHOT and then refresh deps.
