### ISSUE TITLE
Fabric doesn't detect mods on the classpath: "unmet dependencies"

### ISSUE THREAD

**Issue by NightEule5** [FabricMC/fabric-loom#553]
When I run a mod in a dev environment with dependencies declared in the `fabric.mod.json`, with the same dependencies on the classpath (modImplementation), Fabric doesn't detect them. I get a "Mod resolution encountered an incompatible mod set!" error. Fabric Loader isn't even detected.

```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-loader, version 0.12.8 or later.
	 - Install fabric-api, version 0.44.0+1.18 or later.
Unmet dependency listing:
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.12.8 or later of fabric-loader, which is missing!
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.44.0+1.18 or later of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-loader, version 0.12.8 or later.
	 - Install fabric-api, version 0.44.0+1.18 or later.
Unmet dependency listing:
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.12.8 or later of fabric-loader, which is missing!
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.44.0+1.18 or later of fabric-api, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 4 more
```

I would've assumed the solution would be to put the Fabric API into my run/mods directory. But I get the same error, except this time there are "inactive" mods:

```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-loader, version 0.12.8 or later.
	 - Install fabric-api, version 0.44.0+1.18 or later.
Unmet dependency listing:
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.12.8 or later of fabric-loader, which is missing!
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.44.0+1.18 or later of fabric-api, which is missing!
Inactive mods:
	 - mod 'Fabric API' (fabric) 0.44.0+1.18, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric API Lookup API (v1)' (fabric-api-lookup-api-v1) 1.4.0+16d92c47c8, reason: same version active
	 - mod 'Fabric Biome API (v1)' (fabric-biome-api-v1) 6.0.1+ded849a9c8, reason: same version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.9+3ac43d95c8, reason: same version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: same version active
	 - mod 'Fabric Commands (v0)' (fabric-commands-v0) 0.2.5+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Containers (v0)' (fabric-containers-v0) 0.1.18+d154e2c6c8, reason: same version active
	 - mod 'Fabric Content Registries (v0)' (fabric-content-registries-v0) 0.4.5+6f53a73dc8, reason: same version active
	 - mod 'Fabric Crash Report Info (v1)' (fabric-crash-report-info-v1) 0.1.8+3ac43d95c8, reason: same version active
	 - mod 'Fabric Dimensions API (v1)' (fabric-dimensions-v1) 2.1.7+43d29571c8, reason: same version active
	 - mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.4.5+6b21378ac8, reason: same version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f17c8, reason: same version active
	 - mod 'Fabric Events Lifecycle (v0)' (fabric-events-lifecycle-v0) 0.2.6+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Game Rule API (v1)' (fabric-game-rule-api-v1) 1.0.10+3ac43d95c8, reason: same version active
	 - mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.3.0+691a79b5c8, reason: same version active
	 - mod 'Fabric Item Groups (v0)' (fabric-item-groups-v0) 0.3.3+3ac43d95c8, reason: same version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: same version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: same version active
	 - mod 'Fabric Loot Tables (v1)' (fabric-loot-tables-v1) 1.0.8+3ac43d95c8, reason: same version active
	 - mod 'Fabric Mining Level API (v1)' (fabric-mining-level-api-v1) 1.0.3+3ac43d95c8, reason: same version active
	 - mod 'Fabric Mining Levels (v0)' (fabric-mining-levels-v0) 0.1.7+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Models (v0)' (fabric-models-v0) 0.3.3+3ac43d95c8, reason: same version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: same version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.5+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Object Builder API (v1)' (fabric-object-builder-api-v1) 1.11.0+3b82842ec8, reason: same version active
	 - mod 'Fabric Object Builders (v0)' (fabric-object-builders-v0) 0.7.8+3ac43d95c8, reason: same version active
	 - mod 'Fabric Particles (v1)' (fabric-particles-v1) 0.2.9+526dc1acc8, reason: same version active
	 - mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.8.5+3ac43d95c8, reason: same version active
	 - mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 0.4.9+3ac43d95c8, reason: same version active
	 - mod 'Fabric Renderer - Indigo' (fabric-renderer-indigo) 0.4.12+3ac43d95c8, reason: same version active
	 - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 3.2.7+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: same version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: same version active
	 - mod 'Fabric Rendering (v0)' (fabric-rendering-v0) 1.1.9+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378ac8, reason: same version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: same version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: same version active
	 - mod 'Fabric Screen Handler API (v1)' (fabric-screen-handler-api-v1) 1.1.11+3ac43d95c8, reason: same version active
	 - mod 'Fabric Structure API (v1)' (fabric-structure-api-v1) 2.0.8+295197a7c8, reason: same version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.5+3ac43d95c8, reason: same version active
	 - mod 'Fabric Textures (v0)' (fabric-textures-v0) 1.0.9+3ac43d95c8, reason: same version active
	 - mod 'Fabric Tool Attribute API (v1)' (fabric-tool-attribute-api-v1) 1.3.4+7de09f55c8, reason: same version active
	 - mod 'Fabric Transfer API (v1)' (fabric-transfer-api-v1) 1.5.5+b4f4f6cdc8, reason: same version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-loader, version 0.12.8 or later.
	 - Install fabric-api, version 0.44.0+1.18 or later.
Unmet dependency listing:
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.12.8 or later of fabric-loader, which is missing!
	 - Mod 'loom-bug' (loom-bug) 0.0.1 requires version 0.44.0+1.18 or later of fabric-api, which is missing!
Inactive mods:
	 - mod 'Fabric API' (fabric) 0.44.0+1.18, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric API Lookup API (v1)' (fabric-api-lookup-api-v1) 1.4.0+16d92c47c8, reason: same version active
	 - mod 'Fabric Biome API (v1)' (fabric-biome-api-v1) 6.0.1+ded849a9c8, reason: same version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.9+3ac43d95c8, reason: same version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: same version active
	 - mod 'Fabric Commands (v0)' (fabric-commands-v0) 0.2.5+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Containers (v0)' (fabric-containers-v0) 0.1.18+d154e2c6c8, reason: same version active
	 - mod 'Fabric Content Registries (v0)' (fabric-content-registries-v0) 0.4.5+6f53a73dc8, reason: same version active
	 - mod 'Fabric Crash Report Info (v1)' (fabric-crash-report-info-v1) 0.1.8+3ac43d95c8, reason: same version active
	 - mod 'Fabric Dimensions API (v1)' (fabric-dimensions-v1) 2.1.7+43d29571c8, reason: same version active
	 - mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.4.5+6b21378ac8, reason: same version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f17c8, reason: same version active
	 - mod 'Fabric Events Lifecycle (v0)' (fabric-events-lifecycle-v0) 0.2.6+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Game Rule API (v1)' (fabric-game-rule-api-v1) 1.0.10+3ac43d95c8, reason: same version active
	 - mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.3.0+691a79b5c8, reason: same version active
	 - mod 'Fabric Item Groups (v0)' (fabric-item-groups-v0) 0.3.3+3ac43d95c8, reason: same version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: same version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: same version active
	 - mod 'Fabric Loot Tables (v1)' (fabric-loot-tables-v1) 1.0.8+3ac43d95c8, reason: same version active
	 - mod 'Fabric Mining Level API (v1)' (fabric-mining-level-api-v1) 1.0.3+3ac43d95c8, reason: same version active
	 - mod 'Fabric Mining Levels (v0)' (fabric-mining-levels-v0) 0.1.7+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Models (v0)' (fabric-models-v0) 0.3.3+3ac43d95c8, reason: same version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: same version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.5+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Object Builder API (v1)' (fabric-object-builder-api-v1) 1.11.0+3b82842ec8, reason: same version active
	 - mod 'Fabric Object Builders (v0)' (fabric-object-builders-v0) 0.7.8+3ac43d95c8, reason: same version active
	 - mod 'Fabric Particles (v1)' (fabric-particles-v1) 0.2.9+526dc1acc8, reason: same version active
	 - mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.8.5+3ac43d95c8, reason: same version active
	 - mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 0.4.9+3ac43d95c8, reason: same version active
	 - mod 'Fabric Renderer - Indigo' (fabric-renderer-indigo) 0.4.12+3ac43d95c8, reason: same version active
	 - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 3.2.7+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: same version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: same version active
	 - mod 'Fabric Rendering (v0)' (fabric-rendering-v0) 1.1.9+b4f4f6cdc8, reason: same version active
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378ac8, reason: same version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: same version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: same version active
	 - mod 'Fabric Screen Handler API (v1)' (fabric-screen-handler-api-v1) 1.1.11+3ac43d95c8, reason: same version active
	 - mod 'Fabric Structure API (v1)' (fabric-structure-api-v1) 2.0.8+295197a7c8, reason: same version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.5+3ac43d95c8, reason: same version active
	 - mod 'Fabric Textures (v0)' (fabric-textures-v0) 1.0.9+3ac43d95c8, reason: same version active
	 - mod 'Fabric Tool Attribute API (v1)' (fabric-tool-attribute-api-v1) 1.3.4+7de09f55c8, reason: same version active
	 - mod 'Fabric Transfer API (v1)' (fabric-transfer-api-v1) 1.5.5+b4f4f6cdc8, reason: same version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 4 more
```

I've attached a test project that reproduces this behavior, along with full debug.log outputs:

[LoomBug.zip](https://github.com/FabricMC/fabric-loom/files/7658607/LoomBug.zip)
[debug (without mod installed).log](https://github.com/FabricMC/fabric-loom/files/7658982/debug.without.mod.installed.log)
[debug (with mod installed).log](https://github.com/FabricMC/fabric-loom/files/7658989/debug.with.mod.installed.log)

**Comment by deirn** [comment]
The mod id for Fabric loader is [`fabricloader`](https://github.com/FabricMC/fabric-loader/blob/master/src/main/resources/fabric.mod.json#L3) while Fabric API is [`fabric`](https://github.com/FabricMC/fabric/blob/1.18/src/main/resources/fabric.mod.json#L3).

**Comment by NightEule5** [comment]
Ok, thanks. I'm dumb lol
