### ISSUE TITLE
Crash on MinecraftProvider.hasRecentValidManifest 

### ISSUE THREAD

**Issue by mezz** [FabricMC/fabric-loom#612]
I'm trying to get set up with Fabric Loom and am running into a bug on `0.11-SNAPSHOT`.

This commit turned [ManifestVersion.java](https://github.com/FabricMC/fabric-loom/blob/dev/0.11/src/main/java/net/fabricmc/loom/configuration/providers/minecraft/ManifestVersion.java) into a `record`: https://github.com/FabricMC/fabric-loom/pull/397

This code tries to instantiate it but there is no default no-arg constructor: https://github.com/FabricMC/fabric-loom/blob/fff4afe4051a905320cdef616c61b7094b66b369/src/main/java/net/fabricmc/loom/configuration/providers/minecraft/MinecraftProvider.java#L165

which crashes
```
No suitable constructor found for type [simple type, class net.fabricmc.loom.configuration.providers.minecraft.ManifestVersion]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: UNKNOWN; line: 1, column: 2]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1080)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
    at net.fabricmc.loom.configuration.providers.minecraft.MinecraftProvider.hasRecentValidManifest(MinecraftProvider.java:222)
    at net.fabricmc.loom.configuration.providers.minecraft.MinecraftProvider.downloadMcJson(MinecraftProvider.java:122)
    at net.fabricmc.loom.configuration.providers.minecraft.MinecraftProvider.provide(MinecraftProvider.java:84)
    at net.fabricmc.loom.configuration.providers.minecraft.MergedMinecraftProvider.provide(MergedMinecraftProvider.java:59)
    at net.fabricmc.loom.configuration.CompileConfiguration.setupMinecraft(CompileConfiguration.java:197)
    at net.fabricmc.loom.configuration.CompileConfiguration.lambda$configureCompile$14(CompileConfiguration.java:150)
```

**Comment by modmuss50** [comment]
Are you using any other plugins that could be using and old version of jackson? I wonder if the input json is malformed somehow, does running with `--refresh-dependencies` fix it?

 Seems really odd that this is the first time ive seen this crash, this code should be heavily intergration/battle tested.

**Comment by mezz** [comment]
It looks like a plugin I'm using, `se.bjurr.gitchangelog.git-changelog-gradle-plugin`, has an older version of Jackson which causes this issue.

**Comment by mezz** [comment]
I worked around this by putting the changelog task into its own subproject, where it can't impact other gradle tools.

**Comment by modmuss50** [comment]
Quite a few people have had issues with the wrong deps beign used, make sure you are defining the loom version (and ideally all your plugins) in the root project (even if you dont use loom in that project) like so:

```
id 'fabric-loom' version '0.12-SNAPSHOT' apply false
```

See how its done in loader here: <https://github.com/FabricMC/fabric-loader/blob/master/build.gradle#L15> In the sub projects you can remove the version.

As far as I can tell this is a gradle issue as it shouldnt be allowing you to define the plugin version in the sub projects as a lot of people do. See the gradle docs [here](https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl) on how to do it correctly.
