### ISSUE TITLE
Unable to remap 1.19 using mojang mappings

### ISSUE THREAD

**Issue by derklaro** [FabricMC/fabric-loom#663]
Might be related to an outdated version of asm (9.2) in tiny-remapper, but it seems like that lwjgl is using some class files which are compiled for Java 19 and asm is unable to analyze them:

```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':modules:bridge'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
	< gradle internals wooo>
Caused by: java.lang.RuntimeException: Failed to setup Minecraft, java.lang.RuntimeException: Failed to remap minecraft
	at net.fabricmc.loom.util.ExceptionUtil.createDescriptiveWrapper(ExceptionUtil.java:45)
	at net.fabricmc.loom.configuration.CompileConfiguration.lambda$configureCompile$12(CompileConfiguration.java:150)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
	< gradle internals wooo>
Caused by: java.lang.RuntimeException: Failed to remap minecraft
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.AbstractMappedMinecraftProvider.provide(AbstractMappedMinecraftProvider.java:76)
	at net.fabricmc.loom.configuration.CompileConfiguration.setupMinecraft(CompileConfiguration.java:214)
	at net.fabricmc.loom.configuration.CompileConfiguration.lambda$configureCompile$12(CompileConfiguration.java:148)
	... 184 more
Caused by: java.lang.RuntimeException: Failed to remap JAR C:\Users\Pasqual\.gradle\caches\fabric-loom\1.19\minecraft-merged.jar with mappings from C:\Users\Pasqual\.gradle\caches\fabric-loom\1.19\loom.mappings.1_19.layered+hash.2198-v2\mappings.tiny
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.AbstractMappedMinecraftProvider.remapJar(AbstractMappedMinecraftProvider.java:151)
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.AbstractMappedMinecraftProvider.remapInputs(AbstractMappedMinecraftProvider.java:123)
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.AbstractMappedMinecraftProvider.provide(AbstractMappedMinecraftProvider.java:72)
	... 186 more
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: error analyzing /META-INF/versions/19/org/lwjgl/panama/Test.class from C:\Users\Pasqual\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.3.1\ae58664f88e18a9bb2c77b063833ca7aaec484cb\lwjgl-3.3.1.jar
Caused by: java.lang.RuntimeException: error analyzing /META-INF/versions/19/org/lwjgl/panama/Test.class from C:\Users\Pasqual\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.3.1\ae58664f88e18a9bb2c77b063833ca7aaec484cb\lwjgl-3.3.1.jar
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:576)
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:73)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:525)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:521)
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:521)
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:73)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:492)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:488)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:574)
	... 7 more
```

**Comment by modmuss50** [comment]
What loom version are you using?

**Comment by derklaro** [comment]
0.12.47

**Comment by modmuss50** [comment]
This is usually caused by loom not beign registered correctly within the root project or by another plugin shading an older asm version. See how loader does it here: <https://github.com/FabricMC/fabric-loader/blob/master/build.gradle#L15>

**Comment by derklaro** [comment]
Moving the plugin to the root project fixed the issue, thank you 🤗
