### ISSUE TITLE
Multi-project setups fail to build

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/fabric-loom#68]
Using subprojects works fine for developing, however a few things go wrong when building.
Specifically, when compiling subprojects, loom fails to find some variables like its own version.

My project: https://github.com/Ladysnake/Satin/tree/87e2e3b1e976ff10302d50edf79a82b4b688b47f
I have a root project, and test mods setup as subprojects that depend on the root project.
Here is the output of the `gradle build` command:
https://gist.github.com/Pyrofab/d499b4a1a1ee8e05b14b91cc330db73f

Even if I provide a `fabric-loom-null.jar` artifact, a second issue pops up when a subproject depends on another via the `modCompile` configuration, where loom searches for the artifact in the repositories rather than the build output.

**Comment by asiekierka** [comment]
Try Loom 0.2.1.

**Comment by Pyrofab** [comment]
Right, I didn't update it on the repo. But it doesn't actually fix anything.

**Comment by modmuss50** [comment]
I had this at one point, make sure you are applying loom on all projects.

**Comment by Pyrofab** [comment]
```gradle
plugins {
    id 'fabric-loom' version '0.2.0-SNAPSHOT'
}

subprojects {
    apply plugin: 'fabric-loom'

    dependencies {
        compile rootProject
    }
}
```
Shouldn't that be enough to apply it ?

**Comment by modmuss50** [comment]
humm, now im at my pc ill take a look

**Comment by modmuss50** [comment]
ok, I worked around the null loom version, but now loom isnt appearing on the annotation processor correctly, not sure how possible this is even to fix without a lot of work.

**Comment by Pyrofab** [comment]
Thanks for the fix, that's enough for me to make things work for now. Still leaving that issue open as all isn't resolved.

**Comment by asiekierka** [comment]
How good is the situation on latest Loom 0.2.1? A lot of subproject fixes have been done in prep for API 0.3...

**Comment by UpcraftLP** [comment]
it works in 0.2.1, but is broken again in 0.2.2.

(this is at refreshing the workspace, not building)

```
> Configure project :Mesh
Fabric Loom: 0.2.2-SNAPSHOT Build(jenkins #6)
:setting up loom dependencies
:setting up mappings (yarn 1.14+build.7)
:providing mcp.mobius.waila:Hwyla:1.14-1.9.16-60 (net.fabricmc.yarn.7)
:providing net.fabricmc:fabric:0.2.7+build.127 (net.fabricmc.yarn.7)
:providing net.fabricmc:fabric-loader:0.4.6+build.141 (net.fabricmc.yarn.7)
:providing io.github.prospector.modmenu:ModMenu:1.5.1-81 (net.fabricmc.yarn.7)
:providing com.jamieswhiteshirt:developer-mode:1.0.11 (net.fabricmc.yarn.7)
:providing whilewewait:whilewewait:1.2.0 (net.fabricmc.yarn.7)
:providing roughly-enough-items:RoughlyEnoughItems:2.7.11.97 (net.fabricmc.yarn.7)
:providing gamemode-numbers-fabric:GamemodeNumbers:1.1.0 (net.fabricmc.yarn.7)
:providing rei-addons:REIAddons:1.1.0 (net.fabricmc.yarn.7)
:providing cloth:ClothEvents:0.3.1.23 (net.fabricmc.yarn.7)
:providing cloth-config:ClothConfig:0.1.3.7 (net.fabricmc.yarn.7)
:providing net.fabricmc:tiny-mappings-parser:0.1.1.8
:providing net.fabricmc:sponge-mixin:0.7.11.20
:providing net.fabricmc:tiny-remapper:0.1.0.33
:providing net.fabricmc:fabric-loader-sat4j:2.3.5.4
:providing com.google.jimfs:jimfs:1.1
:providing org.ow2.asm:asm:7.1
:providing org.ow2.asm:asm-analysis:7.1
:providing org.ow2.asm:asm-commons:7.1
:providing org.ow2.asm:asm-tree:7.1
:providing org.ow2.asm:asm-util:7.1
:providing mcp.mobius.waila:Hwyla:1.14-1.9.16-60 (net.fabricmc.yarn.7) sources
:providing net.fabricmc:fabric:0.2.7+build.127 (net.fabricmc.yarn.7) sources
:providing net.fabricmc:fabric-loader:0.4.6+build.141 (net.fabricmc.yarn.7) sources
:providing com.jamieswhiteshirt:developer-mode:1.0.11 (net.fabricmc.yarn.7) sources
:downloading assets...
adding remap dependencies for task curseforge

> Configure project :
Fabric Loom: 0.2.2-SNAPSHOT Build(jenkins #6)
Setting version: 1.0.0-SNAPSHOT
:setting up loom dependencies
:setting up mappings (yarn 1.14+build.7)
:providing io.github.prospector.modmenu:ModMenu:1.5.1-81 (net.fabricmc.yarn.7)
:providing mcp.mobius.waila:Hwyla:1.14-1.9.16-60 (net.fabricmc.yarn.7)
:providing com.jamieswhiteshirt:developer-mode:1.0.11 (net.fabricmc.yarn.7)
:providing whilewewait:whilewewait:1.2.0 (net.fabricmc.yarn.7)
:providing roughly-enough-items:RoughlyEnoughItems:2.7.11.97 (net.fabricmc.yarn.7)
:providing gamemode-numbers-fabric:GamemodeNumbers:1.1.0 (net.fabricmc.yarn.7)
:providing rei-addons:REIAddons:1.1.0 (net.fabricmc.yarn.7)
:providing cloth:ClothEvents:0.3.1.23 (net.fabricmc.yarn.7)
:providing cloth-config:ClothConfig:0.1.3.7 (net.fabricmc.yarn.7)
:providing net.fabricmc:fabric:0.2.7+build.127 (net.fabricmc.yarn.7)
:providing net.fabricmc:fabric-loader:0.4.6+build.141 (net.fabricmc.yarn.7)
:providing net.fabricmc.synthetic:project :Mesh:0.1.0 (net.fabricmc.yarn.7)
:remapping Mesh-1.0.0-SNAPSHOT.jar (TinyRemapper, intermediary -> named)
adding remap dependencies for task curseforge
adding remap dependencies for task curseforge317730

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Steampunk-Machinery'.
> Illegal char <:> at index 143: D:\Minecraft\Modding Workspace\_fabric\Steampunk-Machinery\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.7.net.fabricmc.synthetic.project :Mesh-0.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 4s
Illegal char <:> at index 143: D:\Minecraft\Modding Workspace\_fabric\Steampunk-Machinery\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.7.net.fabricmc.synthetic.project :Mesh-0.1.0.jar```

**Comment by alothmanmoe** [comment]
Also having this issue with loom 0.2.2 and 0.2.3 with composite build configs, when refreshing the gradle project
https://gist.github.com/8e9cdf15ebad8798011837bf684e171c

**Comment by modmuss50** [comment]
Stack trace:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'TechReborn-1.14.2'.
> Illegal char <:> at index 133: C:\Users\mark\Documents\Modding\1.14\TechReborn\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.21.net.fabricmc.synthetic.project :RebornCore-1-14-0.1.0.jar

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'TechReborn-1.14.2'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:73)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:54)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:682)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:138)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:266)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:179)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:138)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:121)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:74)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 133: C:\Users\mark\Documents\Modding\1.14\TechReborn\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.21.net.fabricmc.synthetic.project :RebornCore-1-14-0.1.0.jar
	at net.fabricmc.loom.util.ModProcessor.remapJar(ModProcessor.java:162)
	at net.fabricmc.loom.util.ModProcessor.handleMod(ModProcessor.java:63)
	at net.fabricmc.loom.util.ModCompileRemapper.remapDependencies(ModCompileRemapper.java:121)
	at net.fabricmc.loom.util.LoomDependencyManager.handleDependencies(LoomDependencyManager.java:113)
	at net.fabricmc.loom.AbstractPlugin.lambda$configureCompile$11(AbstractPlugin.java:277)
	at net.fabricmc.loom.AbstractPlugin$$Lambda$187.00000000F4772890.execute(Unknown Source)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy34.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:187)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:184)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1398)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:193)
	... 92 more

```

**Comment by modmuss50** [comment]
Might be fixed now, can you test on the latest (build 5) of loom 0.2.3?

**Comment by UpcraftLP** [comment]
fixed for me, but still requires all dependency projects to be built at least once, because loom checks whether the build output file exists.

**Comment by modmuss50** [comment]
Do you know where that check is?

**Comment by modmuss50** [comment]
Closing as very old, please open a new issue if you still have this
