### ISSUE TITLE
[Linux] [0.12] [Legacy Minecraft Support] Log4j missing when launching run config in <=1.12.2

### ISSUE THREAD

**Issue by thecatcore** [FabricMC/fabric-loom#682]
The game still run but most log doesn't appear and there is an error message as the first log.
1.7.10:
```
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/home/arthur/.gradle/caches/fabric-loom/1.7.10/net.fabricmc.yarn.1_7_10.1.7.10+build.202206171820-v2/minecraft-merged-named.jar!/META-INF/log4j-provider.properties
 java.lang.ClassNotFoundException: can't load class org.apache.logging.log4j.core.impl.Log4jContextFactory at /home/arthur/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.8.1/4ac28ff2f1ddf05dae3043a190451e8c46b73c31/log4j-core-2.8.1.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:240)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.logging.log4j.spi.Provider.loadLoggerContextFactory(Provider.java:96)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:91)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.patchJndi(Log4jLogHandler.java:113)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.<clinit>(Log4jLogHandler.java:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLogHandler(MinecraftGameProvider.java:367)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:338)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/home/arthur/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.8.1/4ac28ff2f1ddf05dae3043a190451e8c46b73c31/log4j-core-2.8.1.jar!/META-INF/log4j-provider.properties
 java.lang.ClassNotFoundException: can't load class org.apache.logging.log4j.core.impl.Log4jContextFactory at /home/arthur/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.8.1/4ac28ff2f1ddf05dae3043a190451e8c46b73c31/log4j-core-2.8.1.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:240)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.logging.log4j.spi.Provider.loadLoggerContextFactory(Provider.java:96)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:91)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.patchJndi(Log4jLogHandler.java:113)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.<clinit>(Log4jLogHandler.java:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLogHandler(MinecraftGameProvider.java:367)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:338)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```
1.12.2:
```
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/home/arthur/.gradle/caches/fabric-loom/1.12.2/net.fabricmc.yarn.1_12_2.1.12.2+build.202206171821-v2/minecraft-merged-named.jar!/META-INF/log4j-provider.properties
 java.lang.ClassNotFoundException: can't load class org.apache.logging.log4j.core.impl.Log4jContextFactory at /home/arthur/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.8.1/4ac28ff2f1ddf05dae3043a190451e8c46b73c31/log4j-core-2.8.1.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:240)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.logging.log4j.spi.Provider.loadLoggerContextFactory(Provider.java:96)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:91)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.patchJndi(Log4jLogHandler.java:113)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.<clinit>(Log4jLogHandler.java:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLogHandler(MinecraftGameProvider.java:367)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:338)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/home/arthur/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.8.1/4ac28ff2f1ddf05dae3043a190451e8c46b73c31/log4j-core-2.8.1.jar!/META-INF/log4j-provider.properties
 java.lang.ClassNotFoundException: can't load class org.apache.logging.log4j.core.impl.Log4jContextFactory at /home/arthur/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.8.1/4ac28ff2f1ddf05dae3043a190451e8c46b73c31/log4j-core-2.8.1.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:240)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.logging.log4j.spi.Provider.loadLoggerContextFactory(Provider.java:96)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:91)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.patchJndi(Log4jLogHandler.java:113)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.<clinit>(Log4jLogHandler.java:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLogHandler(MinecraftGameProvider.java:367)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:338)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```

**Comment by Player3324** [comment]
output with `-Dfabric.debug.logLibClassification`?

**Comment by thecatcore** [comment]
It doesn't change anything...

**Comment by thecatcore** [comment]
Hm, `runtimeOnlyLog4j` seems to be the issue in 1.12.2 with latest loom.

**Comment by modmuss50** [comment]
runtimeOnlyLog4j is only useable for mc versions that have slf4j. It shouldnt cause this issue tho.

**Comment by thecatcore** [comment]
After looking at the logs again, I've realized in the 1.7.10 log that it mentions log4j 2.8.1 when it is supposed to use 2.0-beta9.
2.0-beta9 is including the "missing" class from the log.

**Comment by thecatcore** [comment]
Hm, 2.8.1 also includes the missing class :flushed:

**Comment by 2000Slash** [comment]
How did you event get Fabric to run such old versions. Isn't it only supporting 1.14 and upwards? Or am I missing something here.

**Comment by Juuxel** [comment]
Fabric Loader can run on any release version of Minecraft, as well as almost all earlier versions too. Not sure if the later refactors after 2019 and 2020 have broken some versions like Classic though.

**Comment by modmuss50** [comment]
You shouldnt be using runtimeOnlyLog4j in older versions.

**Comment by thecatcore** [comment]
It occurs even when the config is not set though.
