### ISSUE TITLE
NPE in runClient in multi-project setup

### ISSUE THREAD

**Issue by NikkyAI** [FabricMC/fabric-loom#70]
```
Could not find refmap definition, will be using default name: multi-mod-core-refmap.json

> Task :featureA:remapJar
Source .JAR not found!

> Task :featureA:build
> Task :featureA:buildNeeded
> Task :featureA:runClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':featureA:runClient'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':featureA:runClient'.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:49)
...
Caused by: java.lang.NullPointerException
	at net.fabricmc.loom.util.RunConfig.clientRunConfig(RunConfig.java:154)
	at net.fabricmc.loom.task.RunTaskBase.getJvmArgs(RunTaskBase.java:128)
```

`Source .JAR not found!` is worrying me a little

apart from that it seems to throw a NPE when getting the jvmArguments because this line throws a NPE `config = configProvider.apply(getProject());`
it seems like either `configProvider` is null or the tasks `getProject()` somehow fails

it seems like other loom tasks fail the same in subprojects, like `cleanLoomBinaries`

a project to reproduce: https://github.com/DaemonicLabs/multi-mod

**Comment by NikkyAI** [comment]
by removing `evaluationDependsonChildren()` it seems to get further but instead crashes on 
```
Exception in thread "main" java.lang.RuntimeException: Entrypoint not found!
	at net.fabricmc.loader.launch.knot.Knot.populateClasspath(Knot.java:243)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:103)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**Comment by modmuss50** [comment]
Closing as very old, please open a new issue if you still have this
