### ISSUE TITLE
Error when downloading Mojang mappings

### ISSUE THREAD

**Issue by KaKusaOAO** [FabricMC/fabric-loom#706]
When I start building my project, Fabric Loom generates this exception while downloading Mojang mappings:
```
net.fabricmc.loom.util.download.DownloadException: Failed to download (https://launcher.mojang.com/v1/objects/99ade839eacf69b8bed88c91bd70ca660aee47bb/client.txt) with expected hash: sha1:99ade839eacf69b8bed88c91bd70ca660aee47bb got e430b52e9a3fb3da00eab06a8284a1cd39c95c16
	at net.fabricmc.loom.util.download.Download.error(Download.java:382)
	at net.fabricmc.loom.util.download.Download.doDownload(Download.java:219)
	at net.fabricmc.loom.util.download.Download.downloadPath(Download.java:150)
	... 178 more
```

I have no idea why it has a different checksum...
I can successfully build my projects on older versions of Fabric Loom but not on 0.13.

**Comment by modmuss50** [comment]
This was fixed. Make sure you using 1.0
