### ISSUE TITLE
ModProcessor may create very long filename

### ISSUE THREAD

**Issue by creeper123123321** [FabricMC/fabric-loom#718]
I'm using ecryptfs, which reduces the max filename (https://unix.stackexchange.com/a/32834)
```java
Caused by: java.nio.file.FileSystemException: /home/user/IdeaProjects/ViaFabric/viafabric-mc18/build/loom-cache/remapped_working/net_legacyfabric_yarn_1_8_9_1_8_9_build_388_v2.net.legacyfabric.legacy-fabric-api-legacy-fabric-entity-events-v1-common-1.0.0+common+ae4aa0d092.jar: File name too long
        at net.fabricmc.loom.configuration.mods.ModProcessor.remapJars(ModProcessor.java:142)
        at net.fabricmc.loom.configuration.mods.ModProcessor.processMods(ModProcessor.java:76)
        ... 180 more
```

**Comment by modmuss50** [comment]
Going to close this in favour of #1164
