### ISSUE TITLE
Mixin remapping is incomplete when compileJava output restored from build cache

### ISSUE THREAD

**Issue by zml2008** [FabricMC/fabric-loom#767]
Kinda a log dump here rn cuz I'm kinda dead, but:

When [building my mod in CI with no source changes](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445), using the gradle-build-action's caching, I get the following error indicating that shadows were not properly remapped:

<details>
<summary>Mixin application failure stacktrace</summary>
```
[00:40:47] [main/ERROR]: Mixin apply for mod adventure-platform-fabric failed adventure-platform-fabric.mixins.json:ResourceLocationMixin from mod adventure-platform-fabric -> net.minecraft.class_2960: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method getNamespace in adventure-platform-fabric.mixins.json:ResourceLocationMixin from mod adventure-platform-fabric was not located in the target class net.minecraft.class_2960. Using refmap adventure-platform-fabric-refmap.json
  org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getNamespace in adventure-platform-fabric.mixins.json:ResourceLocationMixin from mod adventure-platform-fabric was not located in the target class net.minecraft.class_2960. Using refmap adventure-platform-fabric-refmap.json
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:[145](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:147)) ~[fabric-loader-0.14.10.jar:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
  	at net.minecraft.class_2583.method_43869(class_2583.java:34) ~[server-intermediary.jar:?]
  	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) [datafixerupper-5.0.28.jar:?]
  	at net.minecraft.class_2583.<clinit>(class_2583.java:27) [server-intermediary.jar:?]
  	at net.minecraft.class_5250.method_43477(class_5250.java:29) [server-intermediary.jar:?]
  	at net.minecraft.class_2561.method_43471(class_2561.java:440) [server-intermediary.jar:?]
  	at net.minecraft.class_2156.<clinit>(class_2156.java:24) [server-intermediary.jar:?]
  	at net.minecraft.class_[155](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:157).<clinit>(class_155.java:228) [server-intermediary.jar:?]
  	at net.minecraft.server.Main.main(Main.java:64) [server-intermediary.jar:?]
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server.jar:0.11.0]
  [00:40:47] [main/ERROR]: Minecraft has crashed!
  net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server.jar:0.11.0]
  Caused by: java.lang.ExceptionInInitializerError
  	at net.minecraft.class_5250.method_43477(class_5250.java:29) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2561.method_43471(class_2561.java:440) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2[156](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:158).<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
  	at net.minecraft.class_155.<clinit>(class_155.java:228) ~[server-intermediary.jar:?]
  	at net.minecraft.server.Main.main(Main.java:64) ~[server-intermediary.jar:?]
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
  	... 4 more
  Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2960 failed
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
  	at net.minecraft.class_2583.method_43869(class_2583.java:34) ~[server-intermediary.jar:?]
  	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-5.0.28.jar:?]
  	at net.minecraft.class_2583.<clinit>(class_2583.java:27) ~[server-intermediary.jar:?]
  	at net.minecraft.class_5250.method_43477(class_5250.java:29) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2561.method_43471(class_2561.java:440) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
  	at net.minecraft.class_155.<clinit>(class_155.java:228) ~[server-intermediary.jar:?]
  	at net.minecraft.server.Main.main(Main.java:64) ~[server-intermediary.jar:?]
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
  	... 4 more
  Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
  	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:[202](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:204)) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
  	at net.minecraft.class_2583.method_43869(class_2583.java:34) ~[server-intermediary.jar:?]
  	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-5.0.28.jar:?]
  	at net.minecraft.class_2583.<clinit>(class_2583.java:27) ~[server-intermediary.jar:?]
  	at net.minecraft.class_5250.method_43477(class_5250.java:29) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2561.method_43471(class_2561.java:440) ~[server-intermediary.jar:?]
  	at net.minecraft.class_[215](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:217)6.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
  	at net.minecraft.class_155.<clinit>(class_155.java:228) ~[server-intermediary.jar:?]
  	at net.minecraft.server.Main.main(Main.java:64) ~[server-intermediary.jar:?]
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
  	... 4 more
  Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [adventure-platform-fabric.mixins.json:ResourceLocationMixin from mod adventure-platform-fabric] from phase [DEFAULT] in config [adventure-platform-fabric.mixins.json] FAILED during APPLY
  	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:[218](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:220)) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
  	at net.minecraft.class_2583.method_43869(class_2583.java:34) ~[server-intermediary.jar:?]
  	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-5.0.28.jar:?]
  	at net.minecraft.class_2583.<clinit>(class_2583.java:27) ~[server-intermediary.jar:?]
  	at net.minecraft.class_5250.method_43477(class_5250.java:29) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2561.method_43471(class_2561.java:440) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
  	at net.minecraft.class_155.<clinit>(class_155.java:[228](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:230)) ~[server-intermediary.jar:?]
  	at net.minecraft.server.Main.main(Main.java:64) ~[server-intermediary.jar:?]
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
  	... 4 more
  Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getNamespace in adventure-platform-fabric.mixins.json:ResourceLocationMixin from mod adventure-platform-fabric was not located in the target class net.minecraft.class_2960. Using refmap adventure-platform-fabric-refmap.json
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:[234](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:236)) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
  	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
  	at net.minecraft.class_2583.method_43869(class_2583.java:34) ~[server-intermediary.jar:?]
  	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-5.0.28.jar:?]
  	at net.minecraft.class_2583.<clinit>(class_2583.java:27) ~[server-intermediary.jar:?]
  	at net.minecraft.class_5[250](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:252).method_43477(class_5250.java:29) ~[server-intermediary.jar:?]
  	at net.minecraft.class_[256](https://github.com/KyoriPowered/adventure-platform-fabric/actions/runs/3560718477/jobs/5980964445#step:9:258)1.method_43471(class_2561.java:440) ~[server-intermediary.jar:?]
  	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[server-intermediary.jar:?]
  	at net.minecraft.class_155.<clinit>(class_155.java:228) ~[server-intermediary.jar:?]
  	at net.minecraft.server.Main.main(Main.java:64) ~[server-intermediary.jar:?]
  	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
  	... 4 more
```
</details>

Notably, Gradle reports that the status of the `:compileJava` task is `FROM-CACHE`, so Gradle recovered the task output from a separate location. My suspicion is that this only restored the compiled class files, and not the extraSrg (or well, in your case tiny) mappings needed to remap shadows. I'd imagine this would be solvable by declaring those generated files as task outputs, excluding the compile task from the build cache, or worst case just failing the build proactively if build cache is enabled.

**Comment by jpenilla** [comment]
https://github.com/jpenilla/quiet-loom/blob/75a777dee0e9b74bb6b75ab4a1528391140e98f9/patches/0011-Fix-mixin-ap-output-not-being-an-output-file-of-comp.patch this patch seems to resolve the issue for me

**Comment by modmuss50** [comment]
> https://github.com/jpenilla/quiet-loom/blob/75a777dee0e9b74bb6b75ab4a1528391140e98f9/patches/0011-Fix-mixin-ap-output-not-being-an-output-file-of-comp.patch this patch seems to resolve the issue for me

Yeah, that change looks good 👍 Would you be ok if I made a PR with it to this repo? (Or you can do it yourself?) Thanks.

**Comment by jpenilla** [comment]
Yes, fine with me

Thanks
