### ISSUE TITLE
Cannot launch debug client and server if multi byte characters are included in project path

### ISSUE THREAD

**Issue by Gakuto1112** [FabricMC/fabric-loom#781]
## Description
If multi byte characters are included like ``C:\Users\user\Documents\MinecraftModDev\テスト``, Minecraft client and server for debug cannot be launched. If multi byte characters are not included, they works fine.

Stack trace is following.
```
Exception in thread "main" java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:85)
```

## How to reproduce
1. Create Fabric mod project with multi byte characters are included in project folder with IntelliJ IDEA.
2. Do initial setups according from [setup tutorial](https://fabricmc.net/wiki/tutorial:setup).
3. Run Minecraft client or server.
4. An error described above will occur.

## Environments
- Windows 11 Home 21H2
  - Intel® Core™ i7-10700KF
  - 16GB RAM
  - NVIDIA GeForce RTX 3070
- IntelliJ IDEA Community Edition 2022.1.3 build#IC-221.5921.22
  - Japanese Language Pack / 日本語言語パック 221.262
  - Minecraft Development 2022.1-1.5.20

**Comment by SolidBlock-cn** [comment]
It seems to happen occasionally. I have multiple projects, all of which contain non-ascii characters but it just sometimes happen. Most cases they are normal. (Such issue happens again just now for me, so I found this post.)

**Comment by SolidBlock-cn** [comment]
I just discussed in the Discord. One possible solution could be setting "Short command line" to none in the run config.

**Comment by Gakuto1112** [comment]
> It seems to happen occasionally. I have multiple projects, all of which contain non-ascii characters but it just sometimes happen. Most cases they are normal. (Such issue happens again just now for me, so I found this post.)

Minecraft client and server still works fine in my project which created in July 2022 and contains multi byte characters in its project path. But, they won't work in the projects which created recently.
