### ISSUE TITLE
Issue with Injected Interfaces and Unpick causes Unpick to fail

### ISSUE THREAD

**Issue by OroArmor** [FabricMC/fabric-loom#789]
Minimal reproduction: https://github.com/OroArmor/unpick-gensources-fail-with-injected-interface
Clone and then run `./gradlew unpickJar --stacktrace`

<details>
<summary> Output: </summary>
<br>

```
> Configure project :
Fabric Loom: 1.0.16
:remapping 1 mods from modImplementation
:remapping sources

> Task :unpickJar
daomephsta.unpick.api.IClassResolver$ClassResolutionException: Failed to find dev/onyxstudios/cca/api/v3/component/ComponentAccess
        at daomephsta.unpick.cli.Main$JarClassResolver.resolveClass(Main.java:136)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:282)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.inheritsFrom(TargetMethods.java:245)
        at daomephsta.unpick.impl.representations.TargetMethods$TargetMethod.implementedBy(TargetMethods.java:213)
        at daomephsta.unpick.impl.representations.TargetMethods.targets(TargetMethods.java:32)
        at daomephsta.unpick.impl.constantmappers.SimpleAbstractConstantMapper.targets(SimpleAbstractConstantMapper.java:25)
        at daomephsta.unpick.api.ConstantUninliner.processMethodUsage(ConstantUninliner.java:190)
        at daomephsta.unpick.api.ConstantUninliner.findMapper(ConstantUninliner.java:141)
        at daomephsta.unpick.api.ConstantUninliner.transformMethod(ConstantUninliner.java:102)
        at daomephsta.unpick.api.ConstantUninliner.transform(ConstantUninliner.java:70)
        at daomephsta.unpick.cli.Main.unpick(Main.java:82)
        at daomephsta.unpick.cli.Main.main(Main.java:47)
daomephsta.unpick.api.IClassResolver$ClassResolutionException: Failed to find dev/onyxstudios/cca/api/v3/component/ComponentAccess
        at daomephsta.unpick.cli.Main$JarClassResolver.resolveClass(Main.java:136)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:282)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.visit(TargetMethods.java:275)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
        at daomephsta.unpick.impl.representations.TargetMethods$InheritanceChecker.inheritsFrom(TargetMethods.java:245)
        at daomephsta.unpick.impl.representations.TargetMethods$TargetMethod.implementedBy(TargetMethods.java:213)
        at daomephsta.unpick.impl.representations.TargetMethods.targets(TargetMethods.java:32)
        at daomephsta.unpick.impl.constantmappers.SimpleAbstractConstantMapper.targets(SimpleAbstractConstantMapper.java:25)
        at daomephsta.unpick.api.ConstantUninliner.processUsage(ConstantUninliner.java:205)
        at daomephsta.unpick.api.ConstantUninliner.findMapper(ConstantUninliner.java:147)
        at daomephsta.unpick.api.ConstantUninliner.transformMethod(ConstantUninliner.java:102)
        at daomephsta.unpick.api.ConstantUninliner.transform(ConstantUninliner.java:70)
        at daomephsta.unpick.cli.Main.unpick(Main.java:82)
        at daomephsta.unpick.cli.Main.main(Main.java:47)

BUILD SUCCESSFUL in 18s
1 actionable task: 1 executed
```
</details>

Note: this does not cause a crash, but should not happen as the CCA classes should be available on the classpath for unpick.

**Comment by zml2008** [comment]
```patch
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: zml <zml@stellardrift.ca>
Date: Tue, 10 Jan 2023 18:43:31 -0800
Subject: [PATCH] fix(unpick): Add mod classpath to unpick

This avoids exceptions thrown by unpick when trying to walk inheritance up
into mod-injected interfaces, which were previously not on the classpath

diff --git a/src/main/java/net/fabricmc/loom/task/UnpickJarTask.java b/src/main/java/net/fabricmc/loom/task/UnpickJarTask.java
index 3ac72fecdf5c890ff695288b3e843feb9ab513d6..e9736bf9cbb685694bc5ccd5a6a4ae1896cd900a 100644
--- a/src/main/java/net/fabricmc/loom/task/UnpickJarTask.java
+++ b/src/main/java/net/fabricmc/loom/task/UnpickJarTask.java
@@ -69,6 +69,7 @@ public abstract class UnpickJarTask extends JavaExec {
 
 		getConstantJar().setFrom(getProject().getConfigurations().getByName(Constants.Configurations.MAPPING_CONSTANTS));
 		getUnpickClasspath().setFrom(getProject().getConfigurations().getByName(Constants.Configurations.MINECRAFT_DEPENDENCIES));
+		getUnpickClasspath().from(getProject().getConfigurations().getByName(Constants.Configurations.MOD_COMPILE_CLASSPATH_MAPPED)); // injected interfaces
 	}
 
 	@Override
```

![PeekingCatGIF](https://user-images.githubusercontent.com/629092/211706190-c764dede-f1d0-4827-ba11-bfa72fc2cc5f.gif)

(this could be fixed in unpick too by making everywhere classes are requested gracefully handle missing classes, but that would change assumptions baked into its API which felt higher-impact than just dumping a bunch of things on the classpath after MC/its deps)

**Comment by modmuss50** [comment]
Fixed, thanks.
