### ISSUE TITLE
Using layered mappings (yarn and mojmap) causes incorrect source generation

### ISSUE THREAD

**Issue by Sumandora** [FabricMC/fabric-loom#830]
I wanted to use layered mappings like this:
```groovy
	mappings loom.layered {
		officialMojangMappings()
		mappings("net.fabricmc:yarn:$project.yarn_mappings:v2")
	}
```
Basically using mojmap as fallback for fields and methods, which don't have yarn names, so that I don't use intermediary for these.
I rebuilt sources and the mappings seem to apply correctly, but the game crashes at runtime with the following error:

```
java.lang.IllegalAccessError: failed to access class com.mojang.realmsclient.gui.task.RepeatedDelayStrategy$1 from class net.minecraft.client.util.Backoff (com.mojang.realmsclient.gui.task.RepeatedDelayStrategy$1 and net.minecraft.client.util.Backoff are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2344fc66)
	at net.minecraft.client.util.Backoff.<clinit>(Backoff.java:7)
	at net.minecraft.client.realms.RealmsPeriodicCheckers.<init>(RealmsPeriodicCheckers.java:32)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:611)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at net.minecraft.client.main.Main.main(Main.java:56)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

The `Backoff` class looks like this:

```java
package net.minecraft.client.util;

import com.mojang.logging.LogUtils;
import com.mojang.realmsclient.gui.task.RepeatedDelayStrategy;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import org.slf4j.Logger;

@Environment(EnvType.CLIENT)
public interface Backoff {
    Backoff ONE_CYCLE = new RepeatedDelayStrategy.1();

    long success();

    long fail();

    static Backoff exponential(final int maxSkippableCycles) {
        // ...
    }
}
```
Bytecode:
```
  static <clinit>()V
   L0
    LINENUMBER 7 L0
    NEW com/mojang/realmsclient/gui/task/RepeatedDelayStrategy$1
    DUP
    INVOKESPECIAL com/mojang/realmsclient/gui/task/RepeatedDelayStrategy$1.<init> ()V
    PUTSTATIC net/minecraft/client/util/Backoff.ONE_CYCLE : Lnet/minecraft/client/util/Backoff;
    RETURN
    MAXSTACK = 2
    MAXLOCALS = 0
```

This decompilation (or rather remapping) is obviously wrong, the `RepeatedDelayStrategy` class doesn't even exist in the entire classpath.

The RepeatedDelayStrategy class is the Backoff class in yarn

I've used a mapping viewer and found this:
![image](https://user-images.githubusercontent.com/52950755/218712358-d3fa6e05-99fa-4075-a037-36747c26d954.png)

The problem seems to be, that the first lambda class does not have a mapping on yarn, but has a mapping in mojmap.

It seems that the remapper needs some sort of check to make sure, to not remap subclasses to fallback mappings, if the "root"-class has been remapped by mappings which take higher priority.

**Comment by Phoupraw** [comment]
It can't even build now.
```
Unfixable conflicts
```
```
Mapping source name conflicts detected:
  cqc METHOD b ((Luc;)V) -> [cqc/addAdditionalSaveData, bye/method_5652]
  cqa METHOD r (()Laxv;) -> [bzh/method_5994, cqa/getAmbientSound]
  dyp METHOD a (()Lcom/mojang/serialization/MapCodec;) -> [dyp/codec, eer/method_53969]
  cii METHOD c (()Z) -> [cii/canContinueToUse, cgh/method_6266]
  czi$3 METHOD a ((Ldcs;)Z) -> [daf/method_7680, czi$3/mayPlace]
  dup METHOD o ((Lees;)Z) -> [dup/canAttachTo, dtx/method_24947]
......
```
