### ISSUE TITLE
Downloading assets often fails the first time

### ISSUE THREAD

**Issue by jellysquid3** [FabricMC/fabric-loom#883]
After pull request #880 was merged, Loom seems to sporadically fail to download certain files when running the `:downloadAssets` task. The data buffer appears either truncated or absent in some responses.

Usually, restarting the task allows it to finish downloading the files it was unable to get the first time. Though the specific files it decides to fail on vary between runs.

<details>
<summary>Stack trace</summary>
<pre>
> Configure project :
Fabric Loom: 1.2.7
Exception in thread "pool-5-thread-3" java.io.UncheckedIOException: net.fabricmc.loom.util.download.DownloadException: Failed download after 3 attempts
        at net.fabricmc.loom.util.download.DownloadExecutor.lambda$runAsync$0(DownloadExecutor.java:54)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.fabricmc.loom.util.download.DownloadException: Failed download after 3 attempts
        at net.fabricmc.loom.util.download.DownloadBuilder.withRetries(DownloadBuilder.java:162)
        at net.fabricmc.loom.util.download.DownloadBuilder.downloadPath(DownloadBuilder.java:123)
        at net.fabricmc.loom.util.download.DownloadBuilder.lambda$downloadPathAsync$0(DownloadBuilder.java:119)
        at net.fabricmc.loom.util.download.DownloadExecutor.lambda$runAsync$0(DownloadExecutor.java:50)
        ... 3 more
Caused by: net.fabricmc.loom.util.download.DownloadException: Failed to download file from (https://resources.download.minecraft.net/99/991b421dfd401f115241601b2b373140a8d78572) to (/home/angeline/.gradle/caches/fabric-loom/assets/objects/99/991b421dfd401f115241601b2b373140a8d78572)
        at net.fabricmc.loom.util.download.Download.error(Download.java:442)
        at net.fabricmc.loom.util.download.Download.downloadPath(Download.java:157)
        at net.fabricmc.loom.util.download.DownloadBuilder.lambda$downloadPath$1(DownloadBuilder.java:124)
        at net.fabricmc.loom.util.download.DownloadBuilder.withRetries(DownloadBuilder.java:159)
        ... 6 more
Caused by: net.fabricmc.loom.util.download.DownloadException: net.fabricmc.loom.util.download.DownloadException: Unexpected file length of 97795 bytes, expected 114786 bytes
        at net.fabricmc.loom.util.download.Download.error(Download.java:438)
        at net.fabricmc.loom.util.download.Download.doDownload(Download.java:227)
        at net.fabricmc.loom.util.download.Download.downloadPath(Download.java:154)
        ... 8 more
Caused by: net.fabricmc.loom.util.download.DownloadException: Unexpected file length of 97795 bytes, expected 114786 bytes
        at net.fabricmc.loom.util.download.Download.error(Download.java:434)
        at net.fabricmc.loom.util.download.Download.doDownload(Download.java:224)
        ... 9 more
Exception in thread "pool-5-thread-6" java.io.UncheckedIOException: net.fabricmc.loom.util.download.DownloadException: Failed download after 3 attempts
        at net.fabricmc.loom.util.download.DownloadExecutor.lambda$runAsync$0(DownloadExecutor.java:54)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.fabricmc.loom.util.download.DownloadException: Failed download after 3 attempts
        at net.fabricmc.loom.util.download.DownloadBuilder.withRetries(DownloadBuilder.java:162)
        at net.fabricmc.loom.util.download.DownloadBuilder.downloadPath(DownloadBuilder.java:123)
        at net.fabricmc.loom.util.download.DownloadBuilder.lambda$downloadPathAsync$0(DownloadBuilder.java:119)
        at net.fabricmc.loom.util.download.DownloadExecutor.lambda$runAsync$0(DownloadExecutor.java:50)
        ... 3 more
Caused by: net.fabricmc.loom.util.download.DownloadException: Failed to download file from (https://resources.download.minecraft.net/99/991b421dfd401f115241601b2b373140a8d78572) to (/home/angeline/.gradle/caches/fabric-loom/assets/objects/99/991b421dfd401f115241601b2b373140a8d78572)
        at net.fabricmc.loom.util.download.Download.error(Download.java:442)
        at net.fabricmc.loom.util.download.Download.downloadPath(Download.java:157)
        at net.fabricmc.loom.util.download.DownloadBuilder.lambda$downloadPath$1(DownloadBuilder.java:124)
        at net.fabricmc.loom.util.download.DownloadBuilder.withRetries(DownloadBuilder.java:159)
        ... 6 more
Caused by: net.fabricmc.loom.util.download.DownloadException: No file was downloaded
        at net.fabricmc.loom.util.download.Download.error(Download.java:434)
        at net.fabricmc.loom.util.download.Download.doDownload(Download.java:216)
        at net.fabricmc.loom.util.download.Download.downloadPath(Download.java:154)
        ... 8 more
> Task :downloadAssets FAILED
</pre>
</details>

At the very least, the problems described in my previous issue with the download threads getting stuck is no longer happening, so... hooray! :smile:

**Comment by modmuss50** [comment]
Ive not seen this recently, since this issue was made the downloader has had a few improvements and Mojang's CDN seems to be a lot more stable. Please open a new issue if you can reproduce this with loom 1.4.
