### ISSUE TITLE
"Minecraft game provider couldn't locate the game!" happens if "Shorten Command Line" enabled

### ISSUE THREAD

**Issue by SolidBlock-cn** [FabricMC/fabric-loom#888]
In the Intellij IDEA (Windows 11), if Shorten Command Line is enabled (as the default Loom config), I cannot launch the game, throwing the following:
```
[08:01:28] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
```
The following is the full log:
```
"C:\Program Files\Java\jdk-17\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:1737,suspend=y,server=n -Dfabric.dli.config=D:\文档\Java\extshape\runtest\.gradle\loom-cache\launch.cfg -Dfabric.dli.env=client -Dfabric.dli.main=net.fabricmc.loader.impl.launch.knot.KnotClient -javaagent:C:\Users\ASUS\AppData\Local\JetBrains\IdeaIC2023.1\captureAgent\debugger-agent.jar=file:/C:/Users/ASUS/AppData/Local/Temp/capture.props -Dfile.encoding=UTF-8 @C:\Users\ASUS\AppData\Local\Temp\idea_arg_file105340956 net.fabricmc.devlaunchinjector.Main -username=Solid
已连接到目标 VM, 地址: ''127.0.0.1:1737'，传输: '套接字''
[08:01:28] [WARN] [FabricLoader/Knot]: Class path entries reference missing files: D:\鏂囨。\Java\extshape\out\production\extshape.main, D:\鏂囨。\Java\extshape\.gradle\loom-cache\minecraftMaven\net\minecraft\minecraft-merged-project-@runtest\1.20-pre1-net.fabricmc.yarn.1_20_pre1.1.20-pre1+build.7-v2\minecraft-merged-project-@runtest-1.20-pre1-net.fabricmc.yarn.1_20_pre1.1.20-pre1+build.7-v2.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-api\0.80.3+1.20\fabric-api-0.80.3+1.20.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\pers\solid\brrp-fabric\1.0.0-beta.1-1.20-pre1\brrp-fabric-1.0.0-beta.1-1.20-pre1.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-transfer-api-v1\3.1.6+4d8536c97d\fabric-transfer-api-v1-3.1.6+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-api-lookup-api-v1\1.6.31+4d8536c97d\fabric-api-lookup-api-v1-1.6.31+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-blockrenderlayer-v1\1.1.36+c2e6f6747d\fabric-blockrenderlayer-v1-1.1.36+c2e6f6747d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-client-tags-api-v1\1.0.17+fb8d95da7d\fabric-client-tags-api-v1-1.0.17+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-command-api-v2\2.2.8+fb8d95da7d\fabric-command-api-v2-2.2.8+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-content-registries-v0\4.0.4+b3f2574b7d\fabric-content-registries-v0-4.0.4+b3f2574b7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-convention-tags-v1\1.4.3+9a7c5daa7d\fabric-convention-tags-v1-1.4.3+9a7c5daa7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-data-generation-api-v1\12.1.5+4d8536c97d\fabric-data-generation-api-v1-12.1.5+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-dimensions-v1\2.1.48+cbbb1b3f7d\fabric-dimensions-v1-2.1.48+cbbb1b3f7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-entity-events-v1\1.5.18+4d8536c97d\fabric-entity-events-v1-1.5.18+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-events-interaction-v0\0.5.0+cf56d7947d\fabric-events-interaction-v0-0.5.0+cf56d7947d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-gametest-api-v1\1.2.7+ae0966ba7d\fabric-gametest-api-v1-1.2.7+ae0966ba7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-item-api-v1\2.1.23+4d8536c97d\fabric-item-api-v1-2.1.23+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-item-group-api-v1\4.0.4+b3f2574b7d\fabric-item-group-api-v1-4.0.4+b3f2574b7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-mining-level-api-v1\2.1.44+4d8536c97d\fabric-mining-level-api-v1-2.1.44+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-lifecycle-events-v1\2.2.17+fb8d95da7d\fabric-lifecycle-events-v1-2.2.17+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-loot-api-v2\1.1.34+c53558c77d\fabric-loot-api-v2-1.1.34+c53558c77d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-message-api-v1\5.1.3+fb8d95da7d\fabric-message-api-v1-5.1.3+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-models-v0\0.3.32+fb8d95da7d\fabric-models-v0-0.3.32+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-recipe-api-v1\1.0.13+03ef495b7d\fabric-recipe-api-v1-1.0.13+03ef495b7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-registry-sync-v0\2.2.3+4d8536c97d\fabric-registry-sync-v0-2.2.3+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-screen-handler-api-v1\1.3.24+fb8d95da7d\fabric-screen-handler-api-v1-1.3.24+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-networking-api-v1\1.3.5+fb8d95da7d\fabric-networking-api-v1-1.3.5+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-object-builder-api-v1\11.0.3+4d8536c97d\fabric-object-builder-api-v1-11.0.3+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-particles-v1\1.0.25+f1e4495b7d\fabric-particles-v1-1.0.25+f1e4495b7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-renderer-indigo\1.1.5+81e8c5767d\fabric-renderer-indigo-1.1.5+81e8c5767d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-renderer-api-v1\2.2.9+4d8536c97d\fabric-renderer-api-v1-2.2.9+4d8536c97d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-rendering-data-attachment-v1\0.3.30+afca2f3e7d\fabric-rendering-data-attachment-v1-0.3.30+afca2f3e7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-rendering-fluids-v1\3.0.23+fb8d95da7d\fabric-rendering-fluids-v1-3.0.23+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-rendering-v1\3.0.3+fb8d95da7d\fabric-rendering-v1-3.0.3+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-screen-api-v1\2.0.3+8aafb8877d\fabric-screen-api-v1-2.0.3+8aafb8877d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-api-base\0.4.26+fb8d95da7d\fabric-api-base-0.4.26+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-biome-api-v1\13.0.9+348a9c647d\fabric-biome-api-v1-13.0.9+348a9c647d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-block-api-v1\1.0.8+e022e5d17d\fabric-block-api-v1-1.0.8+e022e5d17d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-crash-report-info-v1\0.2.17+aeb40ebe7d\fabric-crash-report-info-v1-0.2.17+aeb40ebe7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-game-rule-api-v1\1.0.36+b3f2574b7d\fabric-game-rule-api-v1-1.0.36+b3f2574b7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-key-binding-api-v1\1.0.35+fb8d95da7d\fabric-key-binding-api-v1-1.0.35+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-resource-conditions-api-v1\2.3.3+e6c7d4ee7d\fabric-resource-conditions-api-v1-2.3.3+e6c7d4ee7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-resource-loader-v0\0.11.5+bd913b0d7d\fabric-resource-loader-v0-0.11.5+bd913b0d7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-sound-api-v1\1.0.11+fb8d95da7d\fabric-sound-api-v1-1.0.11+fb8d95da7d.jar, D:\鏂囨。\Java\extshape\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_20_pre1_1_20_pre1_build_7_v2\net\fabricmc\fabric-api\fabric-transitive-access-wideners-v1\4.0.6+03ef495b7d\fabric-transitive-access-wideners-v1-4.0.6+03ef495b7d.jar - the game may not load properly!
[08:01:28] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
[08:01:28] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:214)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```
I've confirmed that the issue _does not happen_ when Shorten Command Line is disabled.
![图片](https://github.com/FabricMC/fabric-loom/assets/32444848/f1075572-587c-409b-932f-659874674688)

**Comment by Quintair** [comment]
If relevant:

This may be due to the fact that the project path contains non-ASCII characters, which may cause incompatibility. Try moving the project to paths without non-ASCII characters, or in the startup configuration “Minecraft Client” and “Minecraft Server” set “Shorten command line” from "@argfile (Java 9+)“ to "none”.

In short, there should be no hieroglyphs on the way with the project. Fix the path.

**Comment by SolidBlock-cn** [comment]
I know this, because it is *myself* that added those sentences in the wiki. 

However, it is still the fact that, it may be a *bug*.

**Comment by modmuss50** [comment]
This was somewhat fixed, loom does not apply the shoren command line arg when there are none ASCII chars in the path.

**Comment by SolidBlock-cn** [comment]
Still happens for Loom 1.4.
Also, with Loom 1.4, there is another issue. The class `net.fabricmc.devlaunchinjector.Main` cannot be found unless I manually change the class path to another one (as shown in the image). After changing that to an option prefixed with "`Java.`", the issue happens as shown in the title of this thread, and I have to manually turn off shorten command line to fix it.
I'm not sure whether it is because I have subprojects, but that issue still happens.
![图片](https://github.com/FabricMC/fabric-loom/assets/32444848/bc89690a-8994-43e8-b896-c9db9f2486b7)

**Comment by modmuss50** [comment]
> Still happens for Loom 1.4. Also, with Loom 1.4, there is another issue. The class `net.fabricmc.devlaunchinjector.Main` cannot be found unless I manually change the class path to another one (as shown in the image). After changing that to an option prefixed with "`Java.`", the issue happens as shown in the title of this thread, and I have to manually turn off shorten command line to fix it. I'm not sure whether it is because I have subprojects, but that issue still happens.

This an an intelij issue caused when updating a project to a new intelij version. It happens for even none Minecraft projects. The easyist soltuion is to close the project, delete the .idea folder and then re-open.

**Comment by SolidBlock-cn** [comment]
I remember I tried to delete `.idea` and re-open but that does not solve. But I just now deleted it again and the issue of class not found has been solved.
However, the issue related to shorten command line still exists. The file can be correctly read with UTF-8, however shown in IDE is still incorrect, which identical to the result encoded in GB2312.
![图片](https://github.com/FabricMC/fabric-loom/assets/32444848/4362c018-ff82-44af-884a-c4fbccdd824e)
![图片](https://github.com/FabricMC/fabric-loom/assets/32444848/37b0bf5b-05e2-4b9f-94f3-3b7f653bd290)
![图片](https://github.com/FabricMC/fabric-loom/assets/32444848/70bf3d2a-51a8-47c1-87b0-1a9cd766ef87)

**Comment by SolidBlock-cn** [comment]
Related issue https://youtrack.jetbrains.com/issue/IDEA-340971/Shorten-command-line-encodes-the-argfile-incorrectly
