### ISSUE TITLE
Filter out Realms authentication error in development environment   

### ISSUE THREAD

**Issue by dicedpixels** [FabricMC/fabric-loom#990]
Follow up to https://github.com/FabricMC/fabric-loom/pull/948, the debug log contains a Realms authentication which can be removed in development environments.

```
[21:49:28] [IO-Worker-1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id
[21:49:28] [IO-Worker-1/ERROR] (Minecraft) Couldn't connect to realms
 net.minecraft.client.realms.exception.RealmsServiceException: Realms authentication error with message 'Invalid session id'
	at net.minecraft.client.realms.RealmsClient.execute(RealmsClient.java:432) ~[minecraft-clientOnly-1f338b2c9f-1.20.2-net.fabricmc.yarn.1_20_2.1.20.2+build.4-v2.jar:?]
	at net.minecraft.client.realms.RealmsClient.clientCompatible(RealmsClient.java:218) ~[minecraft-clientOnly-1f338b2c9f-1.20.2-net.fabricmc.yarn.1_20_2.1.20.2+build.4-v2.jar:?]
	at net.minecraft.client.realms.RealmsAvailability.method_52627(RealmsAvailability.java:45) ~[minecraft-clientOnly-1f338b2c9f-1.20.2-net.fabricmc.yarn.1_20_2.1.20.2+build.4-v2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by modmuss50** [comment]
The stacktrace has been removed by your PR, all thats left is the following log line:
`[21:49:28] [IO-Worker-1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id`

I think this is fine to leave, as its not that scary/doesnt cause idea to switch away from the log out.

**Comment by dicedpixels** [comment]
Yep, I mentioned it here: https://github.com/FabricMC/fabric-loom/pull/991#issuecomment-1825058578. The remaining line is a info line. I doubt it would cause any concern.

**Comment by modmuss50** [comment]
Ah, sorry I missed that. Ill close this issue, as I dont think its needed. 

Thanks :)
